
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="zh-cn">
    <meta name="apple-mobile-web-app-capable" content="no"/>
    <meta name="apple-touch-fullscreen" content="yes"/>
    <meta name="format-detection" content="telephone=no,email=no"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="white">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta http-equiv="Expires" content="0">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-control" content="no-cache">
    <meta http-equiv="Cache" content="no-cache">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <title>debug</title>
</head>
<body>

<form id="god_debug">
    <p>
        <!--<input id="price" type="text" name="price" value="1"  placeholder="请输入金额" required> -->
        请选择金额（price 单位分）
        <select id="price" name="price">
            <?php
            foreach($price as $v):?>
                <option value="<?=$v*100?>" <?=$v==49.99? 'selected':''?>><?=$v?>元 ~<?=$v*100?>分</option>
            <?php endforeach; ?>

        </select>
    </p>
    <p>
        请选择格式(format)
        <select id="format" name="format">
            <option value="h5">H5扫描支付</option>
            <option value="app">APP跳转支付</option>
            <option value="json" selected>json</option>
        </select>
    </p>
    <!--p>
        app_secret:<input id="app_secret" type="text"   value=""  placeholder="" >
        <br>
        notify url:<input id="notify_url" type="text"   value="https://qunfu.readface.cn/pay/notify.php"  placeholder="" style="width: 300px;">
        <br>
        retrun url:<input id="return_url" type="text"   value="https://qunfu.readface.cn/pay/return.php"  placeholder=""  style="width: 300px;">
    </p-->
    <p>
    <table>
        <?php
        foreach($data as $k=>$v ):
            ?>
            <tr>
                <td><?=$k?></td>
                <td><input id="<?=$k?>" name="<?=$k?>" type="text"   value="<?=$v?>"  placeholder="" style="width: 300px;">
                </td>
            </tr>
        <?php endforeach; ?>


    </table>
    </p>
</form>

<button type="button" id="submit_btn">确认购买</button>

<p id="good_new">
<div>调试 sign：</div>
<textarea id="debug_sign" style="width: 500px; height: 30px;"></textarea>

<div>调试 post raw：</div>
<textarea id="debug_post" style="width: 500px; height:100px;"></textarea>
<div>调试 curl：</div>
<textarea id="debug_txt" style="width: 500px; height: 150px;"></textarea>
<div>生成sign的 md5 原值与排序（注意编码UTF8 <a href="https://md5jiami.51240.com/" target="_blank">在线验证</a> ）：</div>
<textarea id="debug_md5" style="width: 500px; height: 150px;"></textarea>

</p>


<!-- Jquery files -->
<script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    $().ready(function(){
        $("#submit_btn").click(function(){
            var str= $('#god_debug').serialize();
            //return alert( str );
            $.post(
                "/test/demo/post",   //创建订单
                str,
                function(data){
                    if (data.error == 0){
                        //$(document.body).append(data.html);
                        $('#debug_sign').val(data.sign);
                        $('#debug_post').val(data.post);
                        $('#debug_txt').val(data.html);
                        $('#debug_md5').val(data.md5);
                        //$('#submitdemo1').click();
                    }
                }, "json"
            );
        });
    });
</script>


</body>
</html>