<style>
    .textarea, #editor .dhtml {
        display: inline-block;
        width: 49%;
        height: 100%;
        vertical-align: top;
        box-sizing: border-box;
        padding: 0 20px;
    }

    .textarea {
        border-right: 1px solid #ccc;
        resize: none;
        outline: none;
        background-color: #f6f6f6;
        font-size: 14px;
        font-family: 'Monaco', courier, monospace;
        padding: 20px;
    }

    code {
        color: #f66;
    }
</style>

<wenda>
    <div class="dr-sim"  v-show="st.edit">
        <div class="dr-sim-close" @click="st.edit=false"><i class="icon-tb-close sui-icon"></i></div>
        <div class="dr-vue" style="max-width: 1240px">
            <h3 style="text-align: center" v-html="st.title" v-if="st.title"></h3>
            <div style="text-align: center; padding: 10px 0;" >
                <input type="text" placeholder="请输入主题，限制在200字内" class="input-xxlarge input-xfat" style="width: 90%;" v-model="f.title">
                <br><br>
                <a href="javascript:void(0);" class="sui-btn btn-large btn-primary" @click="post()" v-if="st.edit===1">新增</a>
                <a href="javascript:void(0);" class="sui-btn btn-large btn-primary" @click="editPost()" v-if="st.edit===2">保存修改</a>
            </div>
            <div id="editor" style="height: 600px;">
                <textarea v-model="f.text" style="overflow: auto"  placeholder="请输入详情" class="textarea"></textarea>
                <div style="overflow: auto" class="dhtml" v-html="compiledMarkdown"></div>
            </div>
        </div>
    </div>
</wenda>

<script>
    var ve_wenda= new Vue({
        el:'wenda',
        computed: {
            compiledMarkdown: function () {
                if( this.f.text=='' ) {
                    return '<div style="padding-top:50px;text-align: center ">请在左边输入详情内容</div>';
                }
                //return marked( this.f.text, { sanitize: true })
                var str= this.f.text;
                str = str.replace(/</ig,'&lt;').replace(/>/ig,'&gt;')
                return str.nl2br();
            }
        },
        data:{
            st:{edit:false,title:'' ,success:function () { }            }
            ,f:{ text: '',title:'',cat_id:0,wenda_id:0 ,novel_id:0   }


        }
        ,methods:{
            go:function (v) {
                console.warn('v',v );
                HC.extend()
            }
            ,post:function () {
                if(this.f.title==''){
                    DR.tip('请输入主题'); return ;
                }
                if(this.f.text==''){
                    DR.tip('请输入内容'); return ;
                }
                var that = this;
                DR.ajax( '/wenda/one/post',{ data: this.f},{success:function (rep ) {
                    console.log('v',rep );
                    vm.st.edit=false;
                    that.st.success(rep);
                }});
            }
            ,editPost:function () {

            }
        }
    });
</script>