
<!--标准mui.css-->
<link rel="stylesheet" href="<?=$hc_app?>/mui/css/mui.min.css">
<script src="<?=$hc_app?>/js/mui.min.js"></script>
<script src="<?=$hc_app?>/js/vue.min.js"></script>
<!--
<script src="<?=$hc_app?>/js/dc.js<?=$local_version?>"></script>
-->
<script src="<?=$hc_app?>/js/hc_v2.js<?=$local_version?>"></script>


<?php if($ma['pf']=='wo'):?>
<link rel="stylesheet" href="<?=$hc_app?>/wo/wo.css?d=2019110102">
<?php endif;?>