<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>HI PAY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <?php include "bk_head.phtml";?>
    <script src="<?=$hc_app?>/js/qf.icomet.js<?=$local_version?>"></script>
    <style>
        .title{
            margin: 20px 15px 7px;
            color: #6d6d72;
            font-size: 15px;
        }
        .fade-enter-active, .fade-leave-active {
            transition: opacity .5s;
        }
        .fade-enter, .fade-leave-to  {
            opacity: 0;
        }
        .q_warng{  margin: 10px 15px 7px;  color: #ff7300; font-size: 15px;  }

        .q_time{position: absolute; right: 83px; top: 11px;}
        .q_btn{ position: absolute; right: 10px;top: 13px; }
        .mui-popup-input input{ height: 40px; font-size: 20px;  font-weight:bolder; }
    </style>
</head>
<body>
<bobo>
    <header class="mui-bar mui-bar-nav">
        <a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left" @click="closeWin()"></a>
        <h1 class="mui-title" v-if="st.alipay.uid && st.ds" v-html="'UID:'+st.alipay.uid"  @click="st.ds=!st.ds"></h1>
        <h1 class="mui-title" v-else-if="st.alipay.account" v-html="'账号:'+st.alipay.account" @click="st.ds=!st.ds"></h1>
        <h1 class="mui-title" v-else>京东网银</h1>

    </header>

    <div class="mui-content">
        <div class="mui-input-group" style="margin-top: 5px; ">

            <div class="mui-button-row">
                <button type="button" class="mui-btn " :class="{'mui-btn-primary':st.alipayType==4} " @click="openLogin(4)">监听京东</button>

                <button type="button" class="mui-btn " @click="clear()">清空</button>

                <template  v-if="!st.isOpen">
                    <button type="button" class="mui-btn " @click="logOut( )" v-if="st.alipay.name">登出</button>
                    <!--
                    <button type="button" class="mui-btn " @click="openWin( )" v-else>登录</button>
                    -->
                </template>
                <button type="button" class="mui-btn " @click="closeWin( )" v-else>关闭</button>
                <!--
                <button type="button" class="mui-btn " @click="test()">Test</button>
                -->

            </div>

        </div>

        <div v-if="st.isLogOut" style="padding-top: 50px;text-align: center">
            已经登出，请返回重新开启本页
        </div>
        <template v-else>
            <div class="title">状态:<span v-if="st.loadFailCnt>0" v-html="st.loadFailCnt+'次失败'" style="color: #f0ad4e"></span><span v-else-if="st.isStartIComet">监听</span><span v-else style="color: red">未开启</span>
                ，姓名:<span v-html="st.alipay.name" v-if="st.alipay.name"></span><span v-else style="color: red">未登录</span>

                <span v-html="' ，余额:'+st.alipay.amount+'元'" v-if="st.alipay.amount"></span>
            </div>

            <div class="mui-content-padded">

                <div v-if="postObj.id!='' ">当前:<span v-html="postObj.id" v-if="postObj.id!=''"></span>  <span v-html="HC.dateUtils.date_format( postObj.time ,'HH:mm:ss' ) " v-if="postObj.time>0"></span></div>
                <div v-if="st.debug.length>0">
                    <div v-for="v in st.debug" >{{v}}</div>
                </div>
            </div>
        </template>


    </div>
</bobo>
</body>
<script>

new Vue({
    el: 'bobo',
    data: {
        st: {
            alipay: {name: '', amount: '', account: '', uid: ''}
            , isStartIComet: false, isOpen: false, iComet: null, ds: false, alipayType: 3
            , isFirst: true, loadFailCnt: 0
            , debug: [],isLogOut:false
        }
        , postObj: {id: '', time: 0}
        , yesObj: {}
        , list: []
        ,last:{time:0, orderNo:'', flashTime:0}
    }
    ,
    created: function () {
    },
    mounted: function () {

        setInterval(this.clientTime, 10 * 1000);
        setTimeout(function () {
            api.setKeepScreenOn({
                keepOn: true
            });
        }, 10000);
    },
    methods: {
        test(){
            //this.fundAccountDetail();
            this.createBill( {id:'12345',amount:'12',bn:'南京银行'});
        },
        clear(){
            this.st.debug=[];
        }
        ,logOut(){
            var f= confirm('确定要登出？');
            if(!f) return ;
            this.st.isLogOut = true;
            this.ajax('https://passport.jd.com/uc/login?ltype=logout&ReturnUrl=https://home.jd.com/');
            this.closeWin();
        }
        ,clientTime:function () {
           // if( this.is)
            if(  this.st.alipay.account=='') return ;
            if(  !this.st.isStartIComet ) return ;
            var f=  this.st.alipay ;
            if( !this.st.isLogOut ) {
                HC.ajax('/client/timeB2JD/' + this.st.alipay.uid, {data: f});
                setTimeout(this.openLogin, parseInt(10 * 1000 * Math.random()));
            }

            this.flash();
            //this.fundAccountDetail();
        }
        ,flash(){
            var conf_dt= this.getFlashDt();
            var dt= this.getTimeNow()-this.last.flashTime;
            if(dt>=conf_dt){
                this.last.flashTime= this.getTimeNow();
                this.fundAccountDetail();
            }

        }
        ,getFlashDt(){
            var fdt= this.getTimeNow()-this.last.time;
            if(fdt<100) return 9;
            if(fdt<200) return 19;
            if(fdt<300) return 29;
            if(fdt<400) return 49;
            if(fdt<600) return 59;
            if(fdt<3600) return 150;
            if(fdt<24*3600) return 300;
            return 600;
        }
        ,fundAccountDetail(){
            var that = this;
            //that.log('god news');
            that.ajax('https://mymoney.jd.com/finance/recently.action',{
                success(res){
                    //that.log( res );
                    var str = that.cut(res,'<div class="d-table-bg" style="display: block;">','<div class="d-tip">');
                   // that.log(str);//
                    var last = that.cut(str,'<td>','</td>');
                    //that.log( last );
                    if( !last && that.last.orderNo) that.log('获取账单错误');

                    if(!last) return;
                    if(last == that.last.orderNo) return;
                    that.last.orderNo= last;
                    //that.log('最新V2:'+ that.last.orderNo);
                    var ds={
                        data: str.replace(/["'\r\n\t]/ig,''),//.replace(/\r\n/g,'').replace(/\t/g,'') , //
                        t:that.getTimeNow(),
                        i:that.st.alipay.uid
                        ,cls:'com.b2jd.bill'
                    }
                    var signature = api.require('signature');
                    let pubStr='ggdNsigbn';
                    ds.s = signature.md5Sync({data: ds.i+ pubStr+ ds.i });

                    that.postSave( ds );
                    that.log('最新:'+ that.last.orderNo);

                }
            });
        }
        ,getTimeNow:function () {
            return Math.round(new Date() / 1000);
        }
        ,log:function (str) {
            var st2='['+ HC.dateUtils.date_format( this.getTimeNow(),'HH:mm:ss' )+']' + str;
            //console.log(st2);
            //alert( st2 );
            this.st.debug.unshift( st2);//=  st2+'<br>' + this.st.debug;
            if(  this.st.debug.length>100 )this.st.debug.pop();
        }
        ,openLogin:function(){
            var that = this;
            if( arguments.length>0 ) this.st.alipayType= arguments[0];

            var url=  this.getUrl();//'https://my.alipay.com/portal/i.htm' ;

            //alert( url );
            //this.openWin();
            this.ajax(url,{success:function (res) {
                    //alert(res);
                    var str='';
                    var uid ='';

                    if( that.st.alipayType==4 ) {
                        //that.log( JSON.stringify( res) );
                        //uid = that.cut(res,'<div><strong>','<');
                        //alert(uid);
                        if( res.Identity && res.Identity.Unick && res.Identity.Name ) {
                            //str = res.Identity.Unick;
                            str = uid= res.Identity.Name.toLowerCase();
                            that.st.alipay.name = res.Identity.Unick;
                        }
                        //alert( that.st.alipay.name );

                    }else{
                        var str= that.cut(res,'id="JAsideMultiAccTrigger" title="','"'); //账号
                        var uid= that.cut(res,"'uid': '", "'"); //uid
                        //名称显示
                        that.st.alipay.name=that.cut(res,'<span id="asideAccountName" class="fn-hide">','</span>'); //
                        //余额
                        that.st.alipay.amount=that.cut(res,'<em class="aside-available-amount">','</em>');
                    }

                    if (!str || !uid) {
                        //that.log("isFirst>>" + that.st.isFirst  );

                        if( that.st.isFirst || that.st.loadFailCnt>3 ) {
                            that.st.isStartIComet = false;
                            that.openWin();
                        }
                        that.st.loadFailCnt++;
                        return;
                    } else {
                        if( that.st.isFirst ) {
                            that.closeWin();
                            that.st.isFirst= false;
                        }
                        that.st.loadFailCnt=0;
                        if (uid && that.st.alipay.uid != uid) that.startIcomet('JD' + uid);
                        else that.st.isStartIComet = true ;
                    }
                    that.st.alipay.account= str;
                    that.st.alipay.uid= uid;
                    //that.st.alipay.amount=that.cut(res,'<em class="aside-available-amount">','</em>');

                }});

            //setTimeout( this.op)
        }
        ,getUrl(){
            return 'https://passport.jd.com/loginservice.aspx?method=Login&&_='+this.getTimeNow();
            return 'https://i.jd.com/user/info';
            return 'https://mymoney.jd.com/finance/recently.action';
        }
        ,openWin:function () {
            this.st.isOpen = true ;
            var url= this.getUrl();
            url= 'https://passport.jd.com/uc/login?ReturnUrl=https%3A%2F%2Fi.jd.com%2Fuser%2Fuserinfo%2FshowBaseInfo.action';
            //this.log(url);

            api.openFrame({
                name: 'b2jd',
                //url: 'https://shanghu.alipay.com/i.htm'
                url: url
                ,headers:{'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36'}
                ,bounces: true,
                rect: { // 推荐使用Margin布局，用于适配屏幕的动态变化
                    marginTop: 120, // main页面距离win顶部的高度
                    marginBottom: 0, // main页面距离win底部的高度
                    w: 'auto' // main页面的宽度 自适应屏幕宽度
                }
            });
            this.st.isOpen= true;
        }
        ,closeWin:function () {
            api.closeFrame({
                name: 'b2jd'//https://authem14.alipay.com/login/index.htm
            });
            this.st.isOpen=false;
        }
        ,startIcomet:function ( channel) {
            var that = this;
            if( that.st.iComet) that.st.iComet.stop();
            config = {
                channel:  channel,
                signUrl: '/icomet/sign',
                subUrl:  '/icomet/sub',
                callback: that.icommetDo
            };
            that.st.iComet= new iComet( config );
            that.st.isStartIComet = true;
        }
        ,icommetDo:function ( content) {
            //
            try{
                //this.log( '命令>>'+content );
                var d= JSON.parse( content );
                if(d.cmd=='qr' ) this.createBill( d.data );
                else if(d.cmd=='bill' ) this.loadBill( d.data );

            }catch (e) {
            }
        }
        ,ajax:function (url) {
            if( !( location.hostname.indexOf('.zahei.com')>0 || location.hostname.indexOf('.xyxy521.com')>0 ||  location.hostname.indexOf('.atbaidu.com')>0 )){
                HC.msg('x');
                return;
            }
            let that = this;
            var conf={
                data:null
                ,referer: 'https://www.jd.com/'
                ,success:function (res) {   }
                ,dataType:'text'
                ,headers: {  }
            };
            if( arguments.length>1) mui.extend( conf,arguments[1], false );
            conf.headers.referer= conf.referer;
            if( api ) {
                var opt={
                    url: url,
                    method:  'get'
                    ,headers:conf.headers
                    //,dataType:'text'
                };
                if(  conf.data){
                    opt.data={values: conf.data };
                    opt.method='POST';
                };
                api.ajax(opt, function (ret, err) {
                    if (ret) {
                        //alert('成功'+JSON.stringify(ret)  );
                        //success(ret );
                        var str =  ret.body? ret.body: ret;
                    } else {
                        //HC.msg('失败！'+JSON.stringify(err)  );
                        var str = err.body;
                    }
                    conf.success(str);
                });
            }else{

                var opt={
                    dataType:'json',//服务器返回json格式数据
                    type:'get',//HTTP请求类型
                    timeout:10000,//超时时间设置为10秒；
                    //headers:{'Content-Type':'application/json'},
                    success: success,
                    error:function(xhr,type,errorThrown){
                        alert('失败！'+type );
                        //异常处理；
                        console.log(type);
                    }
                };
                if( opt.data!=null ){
                    opt.data = conf.data;
                    opt.type='post';
                }
                mui.ajax( url,opt);
            }
        }
        ,cut2arr:function (str,start,end) {
            var conf={
                re:[],
                start:0
            };
            if( arguments.length>3) mui.extend( conf,arguments[3], false );

            var s_pos= str.indexOf( start , conf.start );
            if(s_pos<0)  return  conf.re ;
            s_pos+= start.length ;
            var e_pos= str.indexOf(end, s_pos );
            if(e_pos<0)   return  conf.re ;
            re.push( str.substr(s_pos,e_pos-s_pos ) );
            conf.start= s_pos+end.length;
            this.cut2arr(str,start,end, conf )
        }
        ,cut:function (str,start,end) {
            var s_pos= str.indexOf( start );
            if(s_pos<0)  return  false;
            s_pos+= start.length ;
            var e_pos= str.indexOf(end, s_pos );
            if(e_pos<0)  return  false;

            return str.substr(s_pos,e_pos-s_pos );
        }
        ,rCut(str,start,end){

            if(arguments.length>3){
                str= this.cut(str,'',arguments[3]);
            }
            str= this.reverse(str);

            var r= this.cut(str,this.reverse(end),this.reverse(start));
            if(!r)return false;

            return  this.reverse(r);
        }
        ,reverse(str){
            return str.split("").reverse().join("");
        }
        ,failBill:function ( dvar ) {
            var that = this;
            that.log(  that.postObj.id+' 构建失败');
            that.postObj.id= '';
            that.postObj.time=  0;
        }
        ,postSave:function (data) {
            var that = this;
            data.account =  that.st.alipay.uid;
            HC.ajax('/client/payLogV3B2JD/'+ that.st.alipay.uid , {data:data });
        }
        ,createBill(data){
            var that = this;
            var dvar={orderId:'' ,alipayNo:'',arg: data};

            if( typeof that.yesObj[ data.id ]!='undefined'){
                that.log(  data.id +'重复' );
                return;
            }
            that.log('构建:'+ data.id+ ','+ data.amount+'元,'+data.bn);

            var t_now=  this.getTimeNow();
            if( (t_now- that.postObj.time )<10 ){
                that.log('不到10秒，当前 '+ that.postObj.id );
                return ;
            }
            that.postObj.id= data.id;
            that.postObj.time=  t_now;





            var doB2=function(b2 ) {
                var d={
                    orderId: b2.id
                    ,channelSign:b2.channelSign
                    ,paySign: b2.paySign
                    //,paySign: '3de722ee76ad1a6afa6d1541b8725240d65d75e4685e3b7457efff9b79e3e50c7449776a39ac231b4f847c8a7dd6024d14986fe9d1f082ad29f1032b6eb79b4c741debeafedba17189b73a35edbaab78043141b744c2f5981bc7f98979b90626e0e4e127abf315f7852bafe49b4ea129a242a6b659228133b28c6bb00781457458cc187b1178710eb685322f8e8d91f9'
                    ,riskPageReq: '{"deviceId":"PO3XT4C54LHHVEK4FEDK54VH6GBYQ2C3VZJOE3YX27GCBGATDXQ6QUEJKEQIIIUNMSW45KZXU7MBDVYK3VCX47KMHU","fingerprint":"d5cb0d8c8426568ceb63a6819a97100f"}'
                    ,cardType: 1
                    ,cashierId:''
                };
                var url='https://pcashier.jd.com/gatewayCashier/bankConfirm';
                that.ajax(url, {
                    data: d, success(res) {

                        //that.log(res);
                        var url = that.cut(res, 'action="', '"');
                        var d = {
                            gw: that.cut(res, 'name="gw" value="', '"'),
                            sign: that.cut(res, 'name="sign" value="', '"'),
                            ts: that.cut(res, 'name="ts" value="', '"')
                        };

                        if (!url) {
                            that.log('未获取到 Purl');
                            that.failBill(dvar);
                            return;
                        }

                        that.ajax(url, {
                            data: d, success(res) {
                                //that.log(res);
                                dvar.url = that.cut(res, 'action="', '"');
                                dvar.epccGwMsg = that.cut(res, 'name="epccGwMsg" value="', '"');
                                if (!dvar.epccGwMsg || !dvar.url) {
                                    that.failBill(dvar);
                                    return;
                                }
                                that.postSave({data: JSON.stringify(dvar), 'cls': 'com.b2jd.qr'});
                                that.log(that.postObj.id + ' 构建成功');
                                that.postObj.time = 0;
                                that.yesObj[that.postObj.id] = 1;

                            }
                        });

                    }
                });
            };

            var b2={
                id:5096376,
                channelSign:'3de722ee76ad1a6afa6d1541b8725240f0ab730367588db0feb3f8f486163cc54cf03e3da07b67597ac91dc438e2fdec6a83781911b869751ac2545d2e1d6472a5a78de93f94253f5d444602b72fe27191aa90c0c1610621436c09319ad29b9665e1ec0392ad039fe263e145069ff9ac'
            }
            //doB2(b2);

            //return;

            var doB1=function () {

                var url='https://mymoney.jd.com/recharge/seedApply.action?balance='+data.amount+'&_='+that.getTimeNow();
                //that.log(url);
                //var url='https://mymoney.jd.com/recharge/seedApply.action?balance=91&_=1602600824365';
                that.ajax(url,{ success(res){
                    //that.log(res);
                    var url=that.cut(res,'"message":"','"');

                    if(!url){
                        that.log('获取orderID失败');;
                        that.failBill(dvar);
                        return;
                    }
                    dvar.alipayNo= that.cut(res,'"type":',',"');
                    that.log('orderID>>' + dvar.alipayNo );


                    that.ajax(url,{success(res){
                        //that.log(res);
                        var sign= that.rCut(res,"gatewayBankConfirm('","','1')\">",data.bn );
                        var paySign= that.cut(res,'id="paySign" value="','"');
                        //that.log( paySign );
                        if(!sign){
                            that.log('获取签名失败');
                            that.failBill(dvar);
                            return;
                        }
                        doB2({id:dvar.alipayNo,channelSign:sign,paySign:paySign });
                    }});

                }});
            }
            doB1();
        }
    }
});
</script>
</html>
