<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>HI PAY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <?php include "bk_head.phtml";?>
    <script src="<?=$hc_app?>/js/qf.icomet.js<?=$local_version?>"></script>
    <style>
        .title{
            margin: 20px 15px 7px;
            color: #6d6d72;
            font-size: 15px;
        }
        .fade-enter-active, .fade-leave-active {
            transition: opacity .5s;
        }
        .fade-enter, .fade-leave-to  {
            opacity: 0;
        }
        .q_warng{  margin: 10px 15px 7px;  color: #ff7300; font-size: 15px;  }

        .q_time{position: absolute; right: 83px; top: 11px;}
        .q_btn{ position: absolute; right: 10px;top: 13px; }
        .mui-popup-input input{ height: 40px; font-size: 20px;  font-weight:bolder; }
    </style>
</head>
<body>
<bobo>
    <header class="mui-bar mui-bar-nav">
        <a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left" @click="closeWin()"></a>
        <h1 class="mui-title">微博</h1>
    </header>
    <div class="mui-content">
        <div class="mui-input-group" style="margin-top: 5px; ">

            <div class="mui-button-row">
                <button type="button" class="mui-btn mui-btn-primary" @click="openLogin()">开始监听</button>
                <button type="button" class="mui-btn " @click="clear()">清空</button>

                <button type="button" class="mui-btn " @click="openWibo( )" v-if="!st.isOpen">微博</button>
                <button type="button" class="mui-btn " @click="closeWin( )" v-else>关闭</button>

                <button type="button" class="mui-btn " @click="testCookie( )">Test</button>
                <!--

                <button type="button" class="mui-btn " @click="logout()">登出</button>
                <button type="button" class="mui-btn " @click="getAll('today')">当日</button>
                <button type="button" class="mui-btn " @click="getAll('yesterday')">昨日</button>
                -->
            </div>
        </div>



    </div>
</bobo>
</body>

<script>
    new Vue({
        el: 'bobo',
        data: {
            st:{win:false ,isOpen:false}
        }
        ,
        created: function () {
        },
        mounted: function () {
        },
        methods: {
            openLogin:function () {
                //this.openWibo();
                
            }
            ,clear:function () {
                
            }
            ,openWibo:function () {
                this.st.isOpen = true ;
                api.openFrame({
                    name: 'weibo',
                    //url: 'https://m.weibo.com/'
                    url: 'http://mall.e.weibo.com/h5/redenvelope/create?uicode=10000011&sinainternalbrowser=topnav&portrait_only=1'
                    //,headers:{'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36'}
                    ,bounces: true,
                    rect: { // 推荐使用Margin布局，用于适配屏幕的动态变化
                        marginTop: 120, // main页面距离win顶部的高度
                        marginBottom: 0, // main页面距离win底部的高度
                        w: 'auto' // main页面的宽度 自适应屏幕宽度
                    }
                });
                this.st.win= true;
            }
            ,closeWin:function () {
                api.closeFrame({
                    name: 'weibo'
                });
                this.st.isOpen= false;
            }
            ,testCookie(){
                var jsfun='alert(document.cookie);';
                api.execScript({
                    frameName: 'weibo',
                    script: jsfun
                });
            }
        }
    });
</script>
</html>