<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>支付宝充值</title>
</head>
<body>
go
</body>
<script>
    var url='<?=$url?>';

    var sdkPayUrl = "astxq://web/webview?url=" + encodeURIComponent( url);
    //alert( sdkPayUrl );
    window.location = sdkPayUrl;
</script>
</html>