<html><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        html,body{color:#333;margin:0;height:100%;font-family:"Myriad Set Pro","Helvetica Neue",Helvetica,Arial,Verdana,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-weight:normal}
        *{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}a{text-decoration:none;color:#000}



        html, body {
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background: #ffffff;
        }
        .pay-btn2{ background-color:#108ee9 ; border: 1px solid #108ee9; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
    </style>
</head>
<body>
<h1 class="mod-title">
    <span class="ico_log ico-1"></span>
</h1>
<div class="col-xs-12 bg-success text-center"><button class="pay-btn2" onclick="gotopay()">点击直接付款</button></div>
<!--<div class='col-xs-12 bg-success text-center'><button id='paybtn' onclick='addfriend();' class='btn btn-success ' >遇到付款</button></div>-->
<script type="text/javascript">
    //var r ='0.01'>200? Math.floor(Math.random()*80)+20:Math.floor(Math.random()*20);

    var r = Math.floor(Math.random() * 0 + 3);
    var times = 0;//剩余时间,单位秒
    var timeDiv = document.getElementById('time');
    var timeObj = null;
    gotopay();
    function gotopay() {
        window.location.href = '<?=$url?>';
    }

</script></body></html>