<html><head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        html,body{color:#333;margin:0;height:100%;font-family:"Myriad Set Pro","Helvetica Neue",Helvetica,Arial,Verdana,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-weight:normal}
        *{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}a{text-decoration:none;color:#000}



        html, body {
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background: #ffffff;
        }
        .pay-btn2{ background-color:#108ee9 ; border: 1px solid #108ee9; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
    </style>
</head>
<body>
<h1 class="mod-title">
    <span class="ico_log ico-1"></span>
</h1>
<div class="col-xs-12 bg-success text-center"><button class="pay-btn2" onclick="gotopay()">点击直接付款</button></div>
<!--<div class='col-xs-12 bg-success text-center'><button id='paybtn' onclick='addfriend();' class='btn btn-success ' >遇到付款</button></div>-->
<script type="text/javascript">
    //var r ='0.01'>200? Math.floor(Math.random()*80)+20:Math.floor(Math.random()*20);

    var r = Math.floor(Math.random() * 0 + 3);
    var times = 0;//剩余时间,单位秒
    var timeDiv = document.getElementById('time');
    var timeObj = null;
    gotopay();
    function gotopay() {
        window.location.href = "alipays://platformapi/startapp?appId=20000200&actionType=toCard&sourceId=bill&ap_framework_sceneId=20000067&cardNo=%e4%bf%ae%e6%94%b9%e9%87%91%e9%a2%9d%e6%97%a0%e6%b3%95%e5%88%b0%e5%b8%90%2c%e6%8d%9f%e5%a4%b1%e8%87%aa%e8%b4%9f****&bankAccount=李樑&bankName=中国建设银行&bankMark=CCB&money=100&amount=100&REALLY_STARTAPP=true&startFromExternal=false&cardIndex=2003031786339148643&cardNoHidden=true&cardChannel=HISTORY_CARD&orderSource=from";
        //window.location.href = 'alipays://platformapi/startapp?appId=20000123&type=qr&actionType=scan&url=alipayqr://platformapi/startapp?saId=10000007&qrcode=https://www.alipay.com/?from=pc&appId=20000123&actionType=scan&biz_data={"s":"money","u":"0","a":"568.01","m":"D318372942222398"}';
        //window.location.href = "alipayqr://platformapi/startapp?saId=10000007&qrcode=https://www.alipay.com/?from=pc&appId=20000123&actionType=scan&biz_data=%7B%22s%22%3A%22money%22%2C%22u%22%3A%220%22%2C%22a%22%3A%22568.01%22%2C%22m%22%3A%22D318372942222398%22%7D";
    }

</script></body></html>