<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>支付宝充值</title>
    <style type="text/css">
        html,body{color:#333;margin:0;height:100%;font-family:"Myriad Set Pro","Helvetica Neue",Helvetica,Arial,Verdana,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-weight:normal}
        *{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}a{text-decoration:none;color:#000}



        html, body {
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background: #ffffff;
        }
    </style>
    <style>
        .demo h1 {
            padding-left: 8px;
            font-size: 24px;
            line-height: 1.2;
            border-left: 3px solid #108EE9;
        }

        .demo h1,
        .demo p {     margin: 1em 0;        }
        .demo .am-button + .am-button,
        .demo .btn + .btn,
        .demo .btn:first-child {
            margin-top: 10px;
        }
        .am-process .am-process-item:first-child .am-icon.process {
            top: 0;
        }

        .am-process .am-icon.process.pay {
            background-position: 0 -24px;
        }

        input {
            display: block;
            padding: 4px 10px;
            margin: 10px 0;
            line-height: 28px;
            width: 100%;
            box-sizing: border-box;
        }
        .jieguo {

            line-height: 26px;
            max-width: 300px;
            padding: 8px 20px;
            margin: 0 auto;
            position: relative;
            border: 1px #ddd dashed;
            box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
            background-color: #f9f9f9;
        }
        .pay-btn2{ background-color:#108ee9 ; border: 1px solid #108ee9; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
        .pay-btn1{ background-color:#ff9713 ; border: 1px solid #ff9713; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 6px;box-sizing: border-box; margin-bottom: 0;    font-size: 14px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;  position:relative; height: 37px;    line-height: 37px;
        }

        .tip p { margin: 8px 0 0 0; font-size:16px;   }
        .tip i { margin: 5px 0 0 0; font-size:16px;   color: #333333 ; display: block; font-style: normal; padding-left: 5px }


        .p-info{ max-width: 600px; padding: 11px; text-align: left; font-size: 14px; margin: 0 auto}
        ul,li{padding: 0;margin: 0; color: #666666; list-style: none}
        .p-info li{padding-top: 5px;  }

        .pay-btn{ background-color:#4cb9fc ; border: 1px solid #33affc; color: #fff;text-decoration:none;
            display: inline-block; padding: 5px 14px;box-sizing: border-box; margin-bottom: 0;    font-size: 14px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 220px;
        }
        .pay-btn-back{ padding-top: 2px;  padding-bottom: 2px; font-size: 12px; width: 100px;     background-color: transparent;
            border: 1px solid #33affc;          color: #33affc;   }
        body{  background-color: #fff }

        .toast-container {     line-height: 17px;  position: fixed; z-index: 9999; bottom: 0px;
            left: 50%;   -webkit-transition:  .3s;   transition: .3s;  -webkit-transform: translate(-50%,0);   transform: translate(-50%,0);
            max-width: 300px; opacity:0;
        }
        .toast-message{  font-size: 14px;padding: 10px 25px;  text-align: center; color: #fff; border-radius: 6px; background-color: #323232;}
        .toast-active{ opacity:0.9; bottom: 50px; }

        .pay-btn2{ background-color:#108ee9 ; border: 1px solid #108ee9; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
        .pay-btn1{ background-color:#ff9713 ; border: 1px solid #ff9713; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }

        .pay-btn3{ background-color:#ea4a36 ; border: 1px solid #e8351f; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
        .tip p { margin: 8px 0 0 0; font-size:18px; font-weight:bold; }
        .tip i { margin: 5px 0 0 0; font-size:16px; font-weight:bold;  color: #333333 ; display: block; font-style: normal;  }

        .pay-btn-group{  border:1px solid   #33affc;  ;   display:flex ;width: 300px; margin: 5px auto; border-radius: 2px; padding: 0; }
        .pay-btn-group .pay-btn-group-txt , .pay-btn-group .pay-btn-group-sb { display: inline-block ;padding: 5px 8px;}
        .pay-btn-group .pay-btn-group-txt{  flex:1 1 ;vertical-align: middle; color: #ff6700;  }
        .pay-btn-group .pay-btn-group-sb{   background-color:#4cb9fc ; border: 1px solid #4cb9fc; color: #fff;text-decoration:none;
            display: inline-block; box-sizing: border-box; margin-bottom: 0;    font-size: 14px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  ;
            user-select: none; margin: 0; }
        .pay-info{ width: 300px;  margin: 15px auto 5px auto; text-align: left;color: #333333 }

        .pay-content-copy{ margin: 0 auto; padding: 20px;   margin-top: 20px;  }



    </style>
</head>
<body style="margin: 0 auto; background-color: #efeff4; ">

<div class="pay-main" style=" padding: 20px; text-align: center;background-color: #ffffff">
    <img src="/res/img/logo_alipay.jpg" style="height: 55px"/>
</div>

<div style="margin: 0 auto; max-width: 480px">


    <div style="padding-top: 10px;text-align: center">充值金额<b style="color: #ff6700; font-size: 40px" id="amount">1.00</b>元</div>

    <div id='jieguo' class='jieguo'  style="display: none" >
        订单：<span style='color:#008bf3' id="remark">12019031100324625919</span>
        <!--<br>金额：<span  style="color: #ff0000" id="amount">200.00 元</span>-->
        <br>状态：<span id='payzt' style="color: #969494">支付中</span>
    </div>

    <div id="ps" style="margin-top: 50px;display: none;">
        <div style="text-align: center;color: #666666">当前支付人数过多，请稍候...</div>
        <div style=" width: 70%; margin: 0 auto; background-color: rgba(0,0,0,0.1); border-radius: 3px;  ">
            <span id="process" style="width: 59%; color:#FFFFFF; background-color: #1E9FFF;display: inline-block; text-align: center">59%</span>
        </div>
        <div style="text-align: center;color: red">进度加载过程中请勿黑屏</div>
    </div>

    <div>

        <div id="ptBtn"  >
            <div style="padding: 20px;display: none;">
                <div style="text-align: center;  ">
                    网页支付:获取短信验证码登录<br>
                    <span style="color: #666666">仅首次需要验证码</span>
                </div>
                <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="pay()"  >打开网页支付(成功率100%)</button></div>

                <div style="text-align: center;padding: 20px">请使用手机号码，下一步进行付款</div>
            </div>



                    <div class="pay-content-copy" style="margin-top: 0px; padding-top: 0px;" >
                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="openAidd2('ka2fei')"  >支付宝转卡(飞行模式)</button></div>

                        <div style="text-align: center">助手支付:安装后支付成功率高</div>
                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="openAidd2('sao')"  >助手：支付宝收款</button></div>
                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="openAidd2('zz')"  >助手：支付宝转账</button></div>
                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="openAidd2('url')"  >助手：支付宝码收款</button></div>
                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="openAidd2('ka')"  >助手：支付宝转卡(无需等待)</button></div>
                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn1"   onclick="download()"  >未安装支付助手点击下载(仅一次)</button></div>

                        <div style="text-align: center;padding-top: 20px; "><button class="pay-btn2"   onclick="xiao()"  >小程序</button></div>


                    </div>

            <?php if( $client==101):?>
                <!--
                <div class="pay-content-copy"  >
                    <div style="text-align: center">直接拉起支付</div>
                    <div style="text-align: center;padding-top: 20px; "><button class="pay-btn1"   onclick="goPay()"  >启动支付宝</button></div>
                </div>
                -->
            <?php endif;?>


        </div>


    </div>



    <div style="display: none">
        <span id="xxxx"></span>
        <span id="bts"></span>
    </div>


</div>




</body>

<script>
    function openAidd() {
        var url='https://qf.zahei.com/test/t40/b2';
        //go_href("mdapp://platformapi/startapp?appId=60000038&url=" + encodeURIComponent("alipays://platformapi/startapp?saId=10000007&qrcode=" +encodeURIComponent(url)+ "&scheme=f0f8c13d7740f93d00e472aaa1fed721"));
        go_href("mdapp://platformapi/startapp?appId=60000038&url=" + encodeURIComponent("alipays://platformapi/startapp?saId=10000007&qrcode=" + "http%3A%2F%2Fdddbenxid.wordniu.cn%3A88%2Fpay%2Findex.php%3Fa%3Dqrcodec%26b%3Dindex%26c%3DopenBank%26order_no%3DD318362777524397%26ts%3D120%26type%3D3") + "&scheme=f0f8c13d7740f93d00e472aaa1fed721");

    }

    function openAidd2(p) {
        var url= 'https%3A%2F%2Fqf.zahei.com%2Ftest%2Ft40%2Fb2';
        //("mdapp://platformapi/startapp?appId=60000038&url=" + encodeURIComponent("alipays://platformapi/startapp?saId=10000007&qrcode=" +encodeURIComponent(url)+ "&scheme=f0f8c13d7740f93d00e472aaa1fed721"));
        //go_href("mdapp://platformapi/startapp?appId=60000038&url=" + encodeURIComponent("alipays://platformapi/startapp?saId=10000007&qrcode=" + "http%3A%2F%2Fddd123benxid.atbaidu.com%3A88%2Fpay%2Findex.php%3Fa%3Dqrcodec%26b%3Dindex%26c%3DopenBank%26order_no%3DD318362777524397%26ts%3D120%26type%3D3") + "&scheme=f0f8c13d7740f93d00e472aaa1fed721");


        switch (p) {
            case 'ka2fei':
                return ka2fei();
                break;
            case 'url':
                url='https://qr.alipay.com/fkx10477a9bvr9oxfit3p69';
                break;
            case 'zz':
                url='https%3A%2F%2Fqf.zahei.com%2Ftest%2Ft40%2Fb2zz';
                break;
            case 'sao':
                url='https%3A%2F%2Fqf.zahei.com%2Ftest%2Ft40%2Fb2sao';
                break;
            case 'ka':
            default:
                url='https%3A%2F%2Fqf.zahei.com%2Ftest%2Ft40%2Fb2';
        }
        go_href("mdapp://platformapi/startapp?appId=60000038&url=" + encodeURIComponent("alipays://platformapi/startapp?saId=10000007&qrcode=" + url) + "&scheme=f0f8c13d7740f93d00e472aaa1fed721");
    }
    
    function ka2fei() {
        var qrcode_url = "alipays://platformapi/startapp?appId=09999988&actionType=toCard&sourceId=bill&cardNo=623058***4649297&bankAccount=杨婷&receiverName=杨婷&money=1&amount=1&bankMark=SPABANK&bankName=中国民生银行&cardIndex=2004091878420744574&cardNoHidden=true&cardChannel=HISTORY_CARD&orderSource=from";

        if(window.navigator.onLine==true){
            alert("请打开飞行模式")
        }else{
            location.href= qrcode_url;
        }

    }

    function go_href(url) {
        //alert(url);
        location.href= url;
    }
    function download() {
        var u = navigator.userAgent;
        var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
        if (isiOS) {
            location.href= "https://sapp.link/download/piv7u";
        } else {
            location.href= 'https://itusapp.com:8181/mdstart/AndroidIntentService.apk';
        }

    }

    function xiao() {
        location.href='alipays://platformapi/startapp?appId=2018100961599704&page=pages%2Ftransfer%2Ftransfer%3Famount%3D1.0%26chInfo%3DmoneyBox%26frontBizNo%3DMERC9t2020022214262238I8%26remark%3D2020%26uid%3D2088232932547186';
    }

    //openAidd2();

</script>

</html>