<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>支付宝</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!--
    <meta http-equiv="Refresh" content="0;url=alipays://platformapi/startapp?appId=20000067&__open_alipay__=YES&url=<?=urlencode($url)?>" />
    -->
    <style>
        .p-info{ max-width: 600px; padding: 11px; text-align: left; font-size: 14px; margin: 0 auto}
        ul,li{padding: 0;margin: 0; color: #666666; list-style: none}
        .p-info li{padding-top: 5px;  }

        .pay-btn{ background-color:#4cb9fc ; border: 1px solid #33affc; color: #fff;text-decoration:none;
            display: inline-block; padding: 5px 14px;box-sizing: border-box; margin-bottom: 0;    font-size: 14px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 220px;
        }
        .pay-btn-back{ padding-top: 2px;  padding-bottom: 2px; font-size: 12px; width: 100px;     background-color: transparent;
            border: 1px solid #33affc;          color: #33affc;   }
        body{  background-color: #fff }

        .toast-container {     line-height: 17px;  position: fixed; z-index: 9999; bottom: 0px;
            left: 50%;   -webkit-transition:  .3s;   transition: .3s;  -webkit-transform: translate(-50%,0);   transform: translate(-50%,0);
            max-width: 300px; opacity:0;
        }
        .toast-message{  font-size: 14px;padding: 10px 25px;  text-align: center; color: #fff; border-radius: 6px; background-color: #323232;}
        .toast-active{ opacity:0.9; bottom: 50px; }

        .pay-btn2{ background-color:#108ee9 ; border: 1px solid #108ee9; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
        .pay-btn3{ background-color:  #fff; border: 1px solid #108ee9; color:#108ee9 ;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
        .himg{display: none; }
        .btnTips{ display: none}

        @media screen and (min-width: 680px) {
            .cpanal .p-info{display: none}
            .cpanal .logo{ width: 600px; margin: 0 auto; text-align: left }
            .cpanal .main{width: 680px;margin: 0 auto;}
            .cpanal .cqr{ float: left; width: 300px;}
            .cpanal .himg{display: block; float: right; width: 370px; }
            .cpanal .btnTips{ display: block; background-color: #ff7674; color:#ffffff ; margin: 0px  30px ; padding: 5px 0; }
        }

    </style>
</head>
<script src="/res/js/qrcode.ajax.min.js"></script>
<body style="margin: 0 auto; background-color: #f7f7f7">
<div class="toast-container" id="toast" ><div class="toast-message" id="toast-txt"></div></div>



<div style="text-align: center;"  class="cpanal" >
    <div style="background-color: #ffffff ; padding-top: 5px; " >
        <div class="logo"><img src="/res/img/logo_alipay.jpg"  style="height: 55px"/></div>
    </div>
    <div style="background: url('/res/img/wave.png') repeat-x #ffffff ;padding-bottom: 30px;padding-top: 15px; margin-top: 15px;">
        <div class="main">

            <div style="text-align: center;color: red">扫码加群,发<?=$trade['realprice']/100?></b>元红包</div>

            <div class="cqr">
                <div style="position: relative;height: 210px">
                    <div id="qrText" style="text-align: center; position: absolute;left: 50%;top: 5px;margin-left: -90px;display: none"><img src="/res/img/shi.jpg"   style="height: 180px;"/></div>
                    <div id="qrCode" style="text-align: center; position: absolute;left: 50%;top: 5px;margin-left: -90px;" ></div>
                    <div id="pay_success" style="text-align: center; position: absolute;left: 50%;top: 5px;margin-left: -90px;display: none">
                        <div style="text-align: center; padding-top: 80px;width: 180px; height: 180px;color: green;font-size: 20px; font-weight: bolder">订单支付成功！</div>
                    </div>

                </div>
                <p class="btnTips">↑打陶宝扫描二维码↑<br><?php if($msgTips): ?><?=$msgTips?><?php else:?>使用支付宝付款<?php endif;?></p>
                <div style="padding-top: 0px">金额<b style="color: #ff6700; font-size: 40px" id="money"><?=$trade['realprice']/100?></b>元</div>
                <div style="padding-top: 20px">订单号：<?=$trade['order_no']?></div>
                <div style="padding-top: 15px;font-size: 14px;" id="timeShow"> ---</div>
                <a id="downloadLink"></a>

            </div>

            <div class="himg">
                <?php if(!$client):?><img src="/res/img/scan.png" /><?php endif; ?>
            </div>
            <div style="clear: both"></div>

            <?php if( $tb_url):?>
                <div  style="max-width: 480px; padding: 20px;" >
                    <div class="pay-btn2" onclick="payTb()">启动淘宝支付</div>
                    <!--
                    <br><br>
                    <div class="pay-btn3" onclick="pay()">启动支付宝支付</div>
                    -->
                </div>
            <?php elseif( $auto): ?>
                <div  style="max-width: 480px; padding: 20px;" >
                    <div class="pay-btn2" onclick="pay()">点我启动支付宝</div>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <?php if( !$auto): ?>
    <div class="p-info" id="p-info" style="max-width: 480px">
        <ul>
            说明：

            <li>1.请<span style="color:red">截图本页</span> 打开淘宝扫一扫 进入相册选择本截图  </li>
            <li>2.加群发单个相应金额的群红包
                <img src="https://cdn.nekoraw.com/res/img/tb1.jpg" width="100%">
            </li>
            <li>
                3.发相应的金额红包<img src="https://cdn.nekoraw.com/res/img/tb2.jpg" width="100%">
            </li>
            <!--
                <li>1.请<span style="color:red">截图本页</span>  </li>
                <li>2.打开支付宝，使用扫一扫
                    <img src="/res/img/s1.png" width="100%">
                </li>
                <li>3.进入相册，再选择本页截图
                    <img src="/res/img/s2.png" width="100%">
                </li>
                -->

        </ul>
    </div>
    <?php endif;?>
</div>

</body>

<script>
    var st={ctime:  Math.round(new Date() / 1000) ,timer:null, qrCode:document.getElementById('qrCode'), qrText:document.getElementById('qrText')
        , pay_main: document.getElementById('pay_main'), pay_success:document.getElementById('pay_success'),p_info:document.getElementById('p-info') ,msg:document.getElementById('msg')
        ,toast:document.getElementById('toast'),'toastTxt': document.getElementById('toast-txt')
        ,btm:document.getElementById('qf_btm'),timeShow: document.getElementById('timeShow'),qrBt:document.getElementById('qrBt')
    };

    function pay() {
        <?php if($tips_pay):?>
        alert("请确保支付宝是关闭状态");

        <?php endif; ?>
        location.href='<?=$url4?>';
    }

    function payTb() {
        location.href='<?=$tb_url?>';
    }

    function back() {
        window.history.go(-1);return false;
    }

    function qrCode( url_text,div_id ) {
        var that = this;
        //console.log( location );
        var qrcode = new QRCode(document.getElementById( div_id ), {
            text: url_text //location.origin  + that.qr.url
            ,width: 180,
            height: 180,
            colorDark : "#000000",
            colorLight : "#ffffff",
            correctLevel : QRCode.CorrectLevel.H
        });
    }

    qrCode('<?=$url?>','qrCode');
    
    function downloadClick() {
        var img = document.getElementById('qrCode').getElementsByTagName('img')[0];
        var canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        canvas.getContext('2d').drawImage(img, 0, 0);
        url = canvas.toDataURL('image/png');
        var downloadLink = document.getElementById('downloadLink');
        downloadLink.setAttribute('href', url);
        downloadLink.setAttribute('download', '<?=$trade['order_no']?>.png');
        downloadLink.click();
    }

    function timeCount(){

        checkPayOrder();
        var now= Math.round(new Date() / 1000);
        var dt= (st.ctime+120  -now );
        //console.log("dt:",dt);
        if( dt<=0 ){
            clearInterval( st.timer );
            st.timeShow.innerText='';
            st.qrCode.style.display='none';
            st.qrText.style.display='block';
            st.timeShow.innerText="已经超时，请重新下单";
            st.qrBt.style.display="none";

        }else{
            st.timeShow.innerHTML="请在<b style='color: #ff6700' >"+ dt +"</b>秒内完成支付";
        }

    }
    st.timer= setInterval( timeCount,1000 );


    <?php if( $auto && $tb_url=='' ): ?>
    window.onload=function(){
        pay();
    }

    <?php endif; ?>

    function checkPayOrder() {
        var now= Math.round(new Date() / 1000);
        console.log("checkPayOrder");
        <?php if($trade['merchant_id']):?>

        if((now-st.ctime)%5==0) {
            ajax_get('/api/checkPay/<?=$trade['merchant_id']?>/<?=$trade['trade_id']?>', function (obj) {
                console.log(obj);
                if (obj.data.is_fu) {
                    clearInterval(st.timer);
                    st.qrText.style.display = 'none';
                    st.qrCode.style.display = 'none';
                    st.pay_success.style.display = 'block';
                }
            });
        }

        <?php endif; ?>
    }

</script>

<script src="//ip.ws.126.net/ipquery"></script>
<script>

    function ajax_get(url,success) {
        var method='get';
        var data= false ;
        var ajax = new XMLHttpRequest();
        if (method=='get') {
            if (data) {
                url+='?';
                url+=data;
            }
            ajax.open(method,url);
            ajax.send();
        }else{
            ajax.open(method,url);
            ajax.setRequestHeader("Content-type","application/x-www-form-urlencoded");
            if (data) {
                ajax.send(data);
            }else{
                ajax.send();
            }
        }
        ajax.onreadystatechange = function () {
            if (ajax.readyState==4&&ajax.status==200) {
                var obj = JSON.parse(  ajax.responseText );
                success( obj );
            }
        }
    }

    function postIP(){
        //console.log("地理位置",lo, lc );
        if(lo==undefined) return ;
        ajax_get('/api/ip/ip/<?=$DR_PVAR[1]?>/<?=$DR_PVAR[0]?>?lo='+ lo+'&lc='+ lc , function (rep) {
            console.log( rep );
        });
    }
    setTimeout(  postIP, 1000);

</script>

</html>
