<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>下单</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no"/>
    <script src="/res/js/clipboard.min.js"></script>
    <style>
        body{ margin: 0 auto; background-color: #f5f5f5}
        .dui-content{ max-width: 600px; margin: 0 auto;  }

        .pay-btn{ background-color:#108ee9 ; border: 1px solid #108ee9; color: #fff;text-decoration:none;
            display: inline-block; padding: 0 4px;box-sizing: border-box; margin-bottom: 0;    font-size: 17px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 100%; position:relative; height: 47px;    line-height: 47px;
        }
        .pay-btn-back{        background-color: #fff; border: 1px solid #c3c3c3; color: #666;   }

        .p-info{ max-width: 600px; padding: 11px; text-align: left; font-size: 14px; margin: 0 auto}
        ul,li{padding: 0;margin: 0; color: #666666; list-style: none}
        .p-info li{padding-top: 5px; }

        .pay-btn-group{  border:1px solid   #33affc;  ;   display:flex ;width: 300px; margin: 5px auto; border-radius: 2px; padding: 0; }
        .pay-btn-group .pay-btn-group-txt , .pay-btn-group .pay-btn-group-sb { display: inline-block ;padding: 5px 8px;}
        .pay-btn-group .pay-btn-group-txt{  flex:1 1 ;vertical-align: middle; color: #ff6700;  }
        .pay-btn-group .pay-btn-group-sb{   background-color:#4cb9fc ; border: 1px solid #4cb9fc; color: #fff;text-decoration:none;
            display: inline-block; box-sizing: border-box; margin-bottom: 0;    font-size: 14px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  ;
            user-select: none; margin: 0; }
        .pay-info{ width: 300px;  margin: 15px auto 5px auto; }

        .toast-container {     line-height: 17px;  position: fixed; z-index: 9999; bottom: 0px;
            left: 50%;   -webkit-transition:  .3s;   transition: .3s;  -webkit-transform: translate(-50%,0);   transform: translate(-50%,0);
            max-width: 300px; opacity:0;
        }
        .toast-message{  font-size: 14px;padding: 10px 25px;  text-align: center; color: #fff; border-radius: 6px; background-color: #323232;}
        .toast-active{ opacity:0.9; bottom: 50px; }

    </style>
</head>
<body>
    <div class="toast-container" id="toast" ><div class="toast-message" id="toast-txt">这是提示信息这是提示信息这是提示信息</div></div>
    <bobo>
        <div style="background-color: #ffffff; padding-bottom: 20px;">
            <div class="dui-content" id="dui-qr-pay">
                <div style="text-align: center;padding-top: 20px;">商户：<?=$merchant['merchant']?> <?=$merchant['merchant_id']?></div>

                <div id="qrCode" style="padding-top: 5px;">
                    <div class="pay-info">请输入金额</div>
                    <div class="pay-btn-group"   >
                        <button class="pay-btn-group-sb"   data-clipboard-target="#cp_account" data-toast="复制账号成功" >金额(元)</button>
                        <div class="pay-btn-group-txt" id="cp_account" style="text-align: right">
                            <input type="text" name="money" v-model="f.money" style="outline-style: none; border: 0;text-align: right; line-height: 20px; font-size: 14px;color: #ff6700 ">
                        </div>
                    </div>

                </div>
                <div id="qrText" style="height: 50px;text-align: center;padding-top: 20px; display: none">
                    <b style="color: #999999;font-size: 16px;">该订单已经超时</b>
                </div>
            </div>
        </div>
        <div style="max-width: 480px; padding: 20px; margin: -20px  auto 0 auto;">
            <div style="text-align: center;padding-top: 20px; "><button class="pay-btn"  @click="callPay()">确认支付</button></div>

        </div>
    </bobo>
</body>
<script type="text/javascript" src="/res/js/vue.min.js"></script>
<script type="text/javascript" src="/res//js/jquery.min.js"></script>
<script type="text/javascript" src="/res//js/dr.js?d=2018091201"></script>
<script type="text/javascript" src="/res//js/art/dialog.js"></script>

<script>
    var st={toast:document.getElementById('toast'),'toastTxt': document.getElementById('toast-txt')};
    function toast( str ) {
        st.toastTxt.innerHTML= str;
        st.toast.classList.add('toast-active');
        setTimeout(function () {
            st.toast.classList.remove('toast-active');
        },3000);
    }
    /*
    var clipboard ;
    window.onload=function () {
        clipboard = new ClipboardJS('.pay-btn-group-sb');
        //clipboard = new ClipboardJS('#pay_sb');
        clipboard.on('success', function(e) {
            console.info('Action:', e.action ,e);
            console.info('Text:', e.text);
            console.info('Trigger:', e.trigger);
            e.clearSelection();
            toast(  e.trigger.getAttribute('data-toast') );
        });

    }
    */
new Vue({
    el: 'bobo',
    data: {
        f:{money:'<?=rand(1,100)?>',mid:'<?=$merchant['merchant_id']?>'}
    }
    ,
    created: function () {
    },
    mounted: function () {
    },
    methods: {
        callPay:function () {
            var data = this.f;
            var that = this;
            DR.ajax('/test/pay/call'  ,{data:data },{success:function (rep) {
                    //that.rz= rep.data.rz;
                    if(rep.data.re.error>0){
                        toast( rep.data.re.error_des );
                        return ;
                    }
                    var url = rep.data.re.data.pay_data.url
                    location.href =url ;
                }});

        }
    }
});

</script>
</html>