<head>
    <link href="https://vjs.zencdn.net/7.1.0/video-js.css" rel="stylesheet">

    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>
</head>

<body>
<video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
       poster="MY_VIDEO_POSTER.jpg" data-setup="{}">
    <source src="http://pgc.cdn.xiaodutv.com/4140545998_4247292126_20170928124528.mp4?authorization=bce-auth-v1%2Fc308a72e7b874edd9115e4614e1d62f6%2F2017-09-28T04%3A45%3A32Z%2F-1%2F%2Fd9f7de9feb04641135e0f0f8d1b9268fcac9c79d01d756efc75151f85c6893cb&responseCacheControl=max-age%3D8640000&responseExpires=Sat%2C+06+Jan+2018+12%3A45%3A32+GMT&xcode=2c870c9d8719cf2d0c5a202dc08eef15fde2e395feb326a8&time=1532738785" type='video/mp4'>

</video>

<script src="https://vjs.zencdn.net/7.1.0/video.js"></script>