<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <?php include "bk_head.phtml";?>
    <style>
        #bohe ul, #bohe li{ padding: 0 ;margin: 0; list-style: none}
        #bohe li{width: 187px; float: left; height: 187px; position: relative }

        #bohe .title{ position: absolute;height: 20px; width: 100%; text-align: center;left: 0;bottom: 0px; background-color: rgba(0,0,0,0.2) ;color: #fff }

    </style>
</head>
<body>
<bobo>
    <div class="mui-content" id="bobo">

        <div id="video" style="height:20px;background-color:#000000;margin:auto;width: 20px;margin-top: -20px;;"></div>
        <div id="bohe" style=" z-index: 11;">
            <!--<ul>
                <li v-for="v in list" @tap="play(v)">
                    <img :src="v.avatar" style="width: 100%;height: 100%">
                    <div class="title mui-ellipsis" v-html="v.user_nicename"></div>
                </li>

            </ul> -->
            <template v-if="list.link.length">
            <div v-for="(v,k) in list.link" class="bb_card">


                <video :src="vPlay.url" style="background-color: #000000"  controls="controls" :width="vPlay.width" height="st.width*0.618"v-if="st.k==k && vPlay.isShow" autoplay="autoplay"></video>
                <div class="mui-card" @tap="play(k)" v-else>
                    <div class="mui-card-header mui-card-media" :style="{'background-image':'url('+list.img[k]+')'}">
                        <div class="fav"><i class="mui-icon icon-tb-likefill" style="font-size: 12px;"></i> <span v-html="list.fav[k]"  ></span></div>
                        <div class="good"><i class="mui-icon icon-tb-appreciatefill" style="font-size: 12px;color: green"></i><span v-html="list.good[k]"  ></span></div>
                        <div class="HD">HD</div>
                    </div>
                    <div class="mui-card-content">
                        <div class="mui-card-content-inner">
                            <p style="color: #333;" v-html="list.name[k]"> </p>

                        </div>
                    </div>
                </div>

            </div>
            </template>
            <div v-else class="bo_loading"></div>
            <div style="clear: both"></div>
        </div>

    </div>
</bobo>
</body>

<script src="<?=$hc_app?>/js/ls.wftpass.list.js<?=$local_version?>"></script>

</html>