<div style="padding: 10px; ">
    <h3>欢迎回来</h3>
    <!--
    <h3>学校</h3>
    <ul class="total"   >
        <li>
            <b><?=$tj_school['school_cnt']?></b>
            <span>总开通</span>
        </li>
        <li>
            <b><?=$tj_school['school_cnt_wait']?></b>
            <span>待跟进</span>
        </li>
    </ul>
    <div style="clear: both;"></div>

    <h3>用户</h3>
    <ul class="total"   >
        <li>
            <b><?=intShow($tj_user['total'])?></b>
            <span>注册</span>
        </li>
        <li>
            <b><?=intShow($tj_user['detail'][1])?></b>
            <span>一般教师</span>
        </li>
        <li>
            <b><?=intShow($tj_user['detail'][3])?></b>
            <span>认证教师</span>
        </li>
        <li>
            <b><?=$tj_user['detail'][2]?></b>
            <span>学生</span>
        </li>
        <li title="昨日注册人数">
            <b><?=$tj_user['yesterday']?></b>
            <span>昨日</span>
        </li>
        <li title="今日注册人数">
            <b><?=$tj_user['today']?></b>
            <span>今日</span>
        </li>
    </ul>
    <div style="clear: both;"></div>
    <h3>读书</h3>
    <ul class="total"   >
        <li>
            <b><?=$tj_book['books_cnt']?></b>
            <span>图书</span>
        </li>
        <li>
            <b><?=intShow($tj_book['user_cnt'])?></b>
            <span>人次</span>
        </li>

        <li>
            <b><?=intShow($tj_book['topic_cnt'])?></b>
            <span>主题</span>
        </li>
        <li>
            <b><?=intShow($tj_book['comment_cnt'])?></b>
            <span>回复</span>
        </li>
        <?php foreach ($tagName as $k => $v ) : if($k<=0) continue;  ?>
            <li>
                <b><?=intShow($tj_book['tag_'.$k.'_cnt'])?></b>
                <span><?=$v['n']?></span>
            </li>
        <?php endforeach;?>
    </ul>

    <div style="clear: both;"></div>
    <h3>阅读过程统计</h3>
    <ul class="total"   >
        <li>
            <b><?=$tj_view['school']?></b>
            <span>学校</span>
        </li>
        <li>
            <b><?=intShow($tj_view['novel'])?></b>
            <span>图书</span>
        </li>
        <li>
            <b><?=intShow($tj_view['user'])?></b>
            <span>用户</span>
        </li>
        <li title="用户看了多少本">
            <b><?=intShow($tj_view['novel_cnt'])?></b>
            <span>本</span>
        </li>
        <li>
            <b><?=intShow($tj_view['cp'])?></b>
            <span>章节</span>
        </li>
        <li>
            <b><?=intShow(intval($tj_view['time']/3600))?>小时</b>
            <span>耗时</span>
        </li>
        <li>
            <b><?=intShow($tj_view['word'])?>字</b>
            <span>字数</span>
        </li>
    </ul>

    <?php if($tj_dict):?>
    <div style="clear: both;"></div>
    <h3>阅读查词</h3>
    <ul class="total"   >
        <li>
            <b><?=$tj_dict['school']?></b>
            <span>学校</span>
        </li>
        <li>
            <b><?=$tj_dict['user']?></b>
            <span>用户</span>
        </li>
        <li>
            <b><?=$tj_dict['novel']?></b>
            <span>小说</span>
        </li>
        <li>
            <b><?=intShow($tj_dict['cp'])?></b>
            <span>次数</span>
        </li>

        <li>
            <b><?=intShow($tj_dict['word'])?> </b>
            <span>单词</span>
        </li>
    </ul>
    <?php endif;?>

    -->
</div>
