<div style="padding: 8px 5px 5px 0px;">
    <form id="user-search" action="<?=R( $_c.'/smsList/s')?>"  class="sui-form pull-left">
        <input type="text" placeholder="手机号码" class="input-medium" name="q" value="<?=$get['q']?>">
        <button type="submit" class="sui-btn ">查找</button>
    </form>
</div>
<table class="sui-table table-bordered">
    <thead>
    <tr>
        <th>手机<br></th>
        <th>时间</th>
        <th>内容</th>
        <th>状态</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach ( $sms['list'] as $v ) : ?>
        <tr>
            <td><?=$v['mobile']?> </td>
            <td><?=date("Y-m-d H:i:s",$v['ctime'])?></td>
            <td><?=$v['content']?></td>
            <td><?=$v['code']==100?'待发':$v['code']?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

<div class="dr-page"><?=$sms['page']?></div>