<script src="<?=$_cdn?><?=$WWW_RES?>/js/plupload/plupload.full.min.js"></script>

<div style="padding: 8px 5px 5px 0px;">
    <form id="user-search" action="<?=R('hcadmin/userlist/search')?>"  class="sui-form pull-left">
        <select name="sq">
            <?php foreach ($sq as $k=>$v): ?>
            <option value="<?=$k?>" <?php if($k==$get['sq']):?>selected<?php endif;?> ><?=$v?></option>
            <?php endforeach; ?>
        </select>
        <input type="text" placeholder="姓名、邮箱、手机号码" class="input-medium" name="q" value="<?=$get['q']?>">
        <input type="text" placeholder="学校名称" class="input-medium" name="school" value="<?=$get['school']?>">

        <button type="submit" class="sui-btn ">查找</button>
    </form>
    <div class=" pull-right" style="padding: 3px 0 0 3px;">
        <!--
        <div class="sui-btn-group">
            <?php foreach ( $ts as $k=> $v ): ?>
                <a class="sui-btn <?php if($k== $ts_key): ?>btn-primary<?php endif; ?>" href="<?=R('hcadmin/userList/ts/'.$k ,'school='. $get['school'] )?>"><?=$v?></a>
            <?php endforeach; ?>
        </div>
        -->
        <div class="sui-btn-group">
        <?php foreach ( $pre_type as $k=> $v ): ?>
            <a class="sui-btn <?php if($k== $pre_key): ?>btn-primary<?php endif; ?>" href="<?=R('hcadmin/userList/pre/'.$k ,'school='. $get['school']  )?>"><?=$v['n']?></a>
        <?php endforeach; ?>
        </div>
    </div>
    <div style="clear: both"></div>
</div>
<?php if ( $userlist['list']  ) : ?>


<table class="sui-table table-bordered">
    <thead>
    <tr>
        <th>UID</th>
        <th>显示昵称</th>
        <th><a href="<?=R( $DR_SELF,['order'=>'login_cnt'])?>">登录次数</a><br>组</th>
        <!--<th>性别<br>角色</th> -->

        <th>最新登录<br>创建</th>
        <th>登录账号</th>
        <th>其他</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ( $userlist['list'] as $v ) : ?>
    <tr>
        <td><?=$v['user_id']?> </td>
        <td><?=$v['name']?><br><?=$v['number']?></td>
        <td><?=$v['login_cnt']?><br><?=$v['school']?></td>
        <!--<td><?=$sex[$v['sex']]?><br><?=$ts[$v['ts']]?></td> -->

        <td><?= $v['last_time']>0? date("Y-m-d H:i", $v['last_time']):'未'?><br><?=date("Y-m-d H:i", $v['ctime'])?></td>
        <td><?php $ik=0; foreach ($v['oauth'] as  $v2): if($ik>0) echo"<br>" ; $ik++; ?><?=$v2['openid']?><?php  endforeach; ?></td>
        <td>
            <?php foreach ( $v['attr'] as $k2=>$v2 ):  ?>
                <?=$attr_type[$k2]['n']?>:<?=$v2[0]['value']?><br>
            <?php endforeach; ?>
        </td>
        <td>
            [<a href="<?=R('hcadmin/user/edit/'. $v['user_id'])?>">编辑</a>]
            <?php if($v['google']):?>
            [<a href="javascript:;" data-url="<?=R('hcadmin/user/clearGoogle/'. $v['user_id'])?>" class="clearGoogle">清谷歌</a>]
            <?php endif;?>
        </td>
    </tr>
    <?php endforeach;?>
    </tbody>
</table>

<?php else: ?>
    <div class="sui-msg msg-large msg-block msg-error">
        <div class="msg-con">该条件下 无匹配结果 <button type="button" data-dismiss="msgs" class="sui-close">×</button> </div>
        <s class="msg-icon"></s>
    </div>
<?php endif; ?>
<div class="flexbox">
    <div class="dr-page flex"><?=$userlist['page']?></div>
    <div style="margin-right: 10px; ">
        <a href="<?=R($_c.'/user/add')?>" class="sui-btn">用户添加</a>
        <button id="upload" class="sui-btn   ">用户导入</button>
        <a href="/res/user.xlsx">模板下载</a>
        <!--
        <a href="<?=R($DR_SELF,'export=excel')?>" class="sui-btn">导出</a>
        -->
    </div>
</div>

<?php include ( tplFile( "hcadmin/i_user.phtml") ); ?>

<script>

    $(function () {
        $('.ajax-url').click( DR.ajaxUrl );
        $('.clearGoogle').click(function () {
            var that = $(this);
            //alert(that.data('url'));
            var url= that.data('url');
            var html='<div><input id="google_code" value="" type="number" style="width: 150px" placeholder="6为数字"></div>';
            var d = dialog({
                title: "谷歌" ,
                content: html
                ,okValue: '提交',
                ok: function () {
                    //alert( );
                    var v= document.getElementById('google_code').value;
                    if( v.length !=6 ){
                        alert("必须6位数字");
                        return false;
                    }
                    DR.ajax( url,{data:{code:v}});
                }
            });
            d.showModal();
        });
        DR.uploadone( 'upload'
            ,{
                cb:function (rep) {
                    alert("成功："+rep.rz.success+"条\n失败："+  rep.rz.error.length +'条' );
                    if(rep.rz.error.length>0 ){
                        var des_str= '';
                        for(var i=0;i< rep.rz.error.length ; i++ ){
                            var dt= rep.rz.error[i];
                            des_str+=  dt.d.A+"："+  dt.error +"<br>";
                        }
                        //DR.tip('<div style="text-align: left;">' + des_str+'</div>' ,{style:'error'});
                        var d = dialog({
                            title: '错误详情',
                            content: '<div style="text-align: center;padding: 10px 15px;text-align: left;"  >'+des_str+'</div>' ,
                            //width:200
                        });
                        d.show();
                    }
                }
                ,query:'abc=123'
                ,url:'<?=R('hcadmin/user/implode')?>'
                ,ext:'xls,xlsx'
            });

    });
</script>
