<form    class="sui-form form-horizontal" novalidate="novalidate" method="post" action="/index/google/post" id="googlePost">


    <div class="control-group">
        <label for="inputEmail" class="control-label"> </label>
        <div class="controls">
            <h3>谷歌验证码</h3>
        </div>
    </div>

    <div class="control-group">
        <label for="inputPassword" class="control-label">谷歌验证码：</label>
        <div class="controls">
            <input type="text"  name="code" placeholder="6位数字" data-rules="required|number" >
        </div>
    </div>

    <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
            <button type="submit" class="sui-btn btn-primary">提交验证</button>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
            <!--帮助：<a href="https://jingyan.baidu.com/article/59703552b7a0b48fc0074099.html" target="_blank">谷歌身份验证器使用教程</a> -->
        <div >首次登录请先 <a href="/member/google"  style="color: red">绑定谷歌身份验证器</a></div>
        </div>
    </div>
</form>

<script>
    $(function () {
        DR.ajaxAndValidate( 'googlePost');

    });
</script>