<div class="dr-min "  >

    <form id="form-msg" class="sui-form form-horizontal" novalidate="novalidate">
        <div class="control-group">
            <label   class="control-label"></label>
            <div class="controls"><h1>登录</h1></div>
        </div>

        <div class="control-group">
            <label class="control-label sui-text-xlarge"  >账号：</label>
            <div class="controls ">
                <input type="text"   id="openid" class="input-xfat" name="openid" placeholder="" data-rules="required">
            </div>
        </div>
        <?php if($loginback=='/merchant'):?>

            <div class="control-group">
                <label class="control-label sui-text-xlarge"  >商户号：</label>
                <div class="controls ">
                    <input type="text"   id="merchant_id" class="input-xfat" name="merchant_id" placeholder="" data-rules="required">
                </div>
            </div>

        <?php endif; ?>
        <?php if($loginback=='/cha'):?>
        <input type="hidden" name="fr" value="cha"/>
        <?php endif; ?>





        <div class="control-group">
            <label for="inputPassword" class="control-label sui-text-xlarge">密码：</label>
            <div class="controls">
                <input type="password"class="input-xfat" id="psw" name="psw" placeholder="密码6到12位"  data-rules="required|minlength=6|maxlength=12">
                <input type="hidden" id="psw_encrypt" name="psw_encrypt" value=""/>
            </div>
        </div>

        <?php if($_GET['sq']):?>

            <div class="control-group">
                <label class="control-label sui-text-xlarge"  >授权码：</label>
                <div class="controls ">
                    <input type="text"   id="sq" class="input-xfat" name="sq" placeholder="有授权码权限更大" data-rules="required">
                </div>
            </div>

        <?php endif; ?>

        <div class="control-group">
            <label for="inputPassword" class="control-label sui-text-xlarge" style="font-size: 13px">谷歌验证码：</label>
            <div class="controls">
                <input type="text"class="input-xfat"  name="google" placeholder="未设置可不填"   >
            </div>
        </div>

        <div class="control-group">
            <label for="sanwei" class="control-label"></label>
            <div class="controls">
                <button type="submit" class="sui-btn btn-primary btn-xlarge">登录</button>

            </div>
        </div>


        <div class="control-group">
            <label for="sanwei" class="control-label"></label>
            <div class="controls">

                <!--
                <div style="width: 190px;"  >
                    <a href="<?=R('forgot')?>"  class="pull-left">找回密码</a> <a href="<?=R('reg')?>"  class="pull-right">马上注册</a>
                </div>
                -->
            </div>
        </div>
    </form>
</div>

<script src="<?=$_cdn?>/res/js/jsencrypt.min.js"></script>
<script>
$(function () {
    DR.loginV2( $('#form-msg') );
});
</script>