<div class="dr-container">
    <ul class="sui-breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="<?=R('book/detail/'.$book['book_id'])?>"><?=$book['book']?></a></li>
        <li class="active"><?=$site_title?></li>
    </ul>

    <h2><?=$site_title?></h2>
    <style>
        .v-hide input{ width: 30px; text-align: center }
    </style>

    <div  class="sp-v2"  >
        <?php if(!$stu['list']):?>
            <div class="dr-box-padding" >
                <div style="text-align: center;padding: 30px 0;" class="sui-text-danger">您暂无任人选课</div>
            </div>
        <?php else:?>

            <div class="dr-box-padding" >
                <form>
                <table class="sui-table ">
                    <thead>

                    <tr>
                        <th>学号、姓名<br>班级</th>
                        <th>任务完成<br><span title="点我设置权重" style="color: #00a0e9;cursor: pointer" >最终分数</span>
                            <div class="v-hide">
                                <button   class="sui-btn btn-small">设置权重</button>
                            </div>
                        </th>
                        <th>讨论/回帖<br>（成绩：<?=$term['dafen'][0]?>）<div class="v-hide"><input type="text"  class="input-mini" name="d0" value="<?=$term['dafen'][0]?>"></div></th>
                        <?php foreach ($tagName as $k=> $v): if($k<=0 ||( $k>0 and $book['tag_'.$k.'_config']==0 ) ) continue; ?>
                            <th><?=$v['n']?><br>（成绩：<?=$term['dafen'][$k]?>）
                                <div class="v-hide"><input type="text"  class="input-mini" name="d<?=$k?>" value="<?=$term['dafen'][$k]?>"></div>
                            </th>
                        <?php endforeach;?>

                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($stu['list'] as $k2=> $var):?>
                        <tr>
                            <td><a href="<?=R('book/user/'.$var['user_id'] )?>" target="_blank"><?=$user[$var['user_id']]['number']?>  <?=$user[$var['user_id']]['name']?>
                                    <br> <?=$class[$var['class_id']]?$class[$var['class_id']]['class']:'-' ?>
                                    <?php if( $term_config['s_end_time']>0 && $var['ctime']>$term_config['s_end_time'] ):?><span class="sui-label label-danger"  >补选</span><?php endif; ?>
                                </a></td>
                            <td><?=$var['finish']['wc_cnt']?'完成':'<span style="color: #999">未</span>'?>
                                <br><?=$var['finish']['score']['last']? $var['finish']['score']['last'] : '-'?>
                            </td>
                            <td><?=$var['topic_cnt']?>/<?=$var['comment_cnt']?><br>(<?=$var['finish']['score'][0]? $var['finish']['score'][0] : '-'?>)</td>
                            <?php foreach ($tagName as $k=> $v): if($k<=0  ||( $k>0 and $book['tag_'.$k.'_config']==0 ) ) continue; ?>
                                <td><?=$var['tag_'.$k.'_cnt']?><?php if($k>3 && isset($var['finish']['sim'][$k]) ): ?><span class="sui-label label-warning"  >相似</span><?php endif;?>
                                    <br>(<?=$var['finish']['score'][$k]? $var['finish']['score'][$k] : '-'?>)</td>
                            <?php endforeach;?>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
                </form>
            </div>
        <?php endif;?>
        <div class="flexbox">
            <div class="dr-page flex"><?=$stu['page']?></div>
            <div><a href="<?=R($DR_SELF,  ['export'=>1,'max'=>3000,'export_total'=>$stu['total_cnt'] ] )?>" class="sui-btn  btn-info">导出</a> </div>
        </div>

    </div>
</div>