<?php if($is_copy):?>
    <div class="dr-box-padding">
        <a href="<?=R('book/index')?>" class="sui-text-large" style="color: red">返回本校</a>
    </div>
    <div class="dr-box-padding"><a href="<?=R('book/book')?>" class="sui-text-large" style="color: red">新增书单</a> </div>
<?php elseif( in_array('p3',$_cu['attr'])): ?>
    <div class="dr-box-padding">
        <a href="<?=R('book/s/hc')?>" class="sui-text-large" style="color: red">好策书库</a>
    </div>
    <div class="dr-box-padding"><a href="<?=R('book/book')?>" class="sui-text-large" style="color: red">新增书单</a> </div>
<?php endif;?>

<?php if( $term_config  && $_a=='index'  ):?>
    <div class="dr-box-padding">
        <div class="dr-box-title" style="color: red">选书通知</div>
        <div class="dr-box-content dr-box-ul">

            <a >选书开始：<?=date('Y-m-d H:i:s',$term_config['s_start_time'])?></a>
            <a >选书截止：<?=date('Y-m-d H:i:s',$term_config['s_end_time'])?></a>
            <?php if( $term_config['book_limit']>0 ):?><a >每位同学最多可选：<?=$term_config['book_limit']?>本</a><?php endif;?>
            <?php if( $term_config['book_limit_min']>0 ):?><a >每位同学不少于选：<?=$term_config['book_limit_min']?>本</a><?php endif;?>
            <a >提交截止：<?=date('Y-m-d H:i:s',$term_config['end'])?></a>
            <?php if($term_config['is_bu']=='1' && time()> $term_config['s_end_time']):?>
                <a style="color: red">已截止可补选，补选成绩扣相应分数</a>
            <?php endif; ?>

        </div>
    </div>
<?php endif;  ?>

<?php if( $topic_news ):?>
    <div class="dr-box-padding">
        <div class="dr-box-title">最新主题</div>
        <div class="dr-box-content dr-box-ul">
            <?php foreach ( $topic_news as $topic ): ?>
                <a href="<?=R('book/topic/'.$topic['topic_id'])?>"><?=$topic['topic']?></a>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;  ?>

<?php if( $booksJoin ): ?>
    <div class="dr-box-padding">
        <div class="dr-box-title">已加入书刊</div>
        <div class="dr-box-content dr-box-ul">
            <?php foreach ( $booksJoin as $join ): ?>
                <a href="<?=R('book/detail/'. $join['book_id_merge']['book_id'])?>"><?=$join['book_id_merge']['book']?></a>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;  ?>

<?php if($comment_hot ):?>
    <div class="dr-box-padding">
        <div class="dr-box-title">热门评论</div>
        <div class="dr-box-content dr-box-ul">
            <?php foreach ( $comment_hot as $topic ): ?>
                <a href="<?=R('book/topic/'.$topic['topic_id'])?>"><?=$topic['topic']?></a>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;  ?>



<div class="dr-box-padding">
    <div class="dr-box-title"  >反馈</div>
    <div class="dr-box-content dr-box-ul">
        <a href="https://jq.qq.com/?_wv=1027&k=4BQUUvo"target="_blank">QQ群：626696890</a>
        <a >邮箱：info@haoce.com</a>
        <a >电话： 010-66026838</a>
    </div>
</div>

<?php include  tplFile("book/i_add.phtml"); ?>



<!--
<div class="dr-box-padding">
    <div class="dr-box-title"  >扫描聊聊反馈</div>
    <div class="dr-box-content dr-box-ul">
         <img src="/res/img/qr-webim.png">
    </div>
</div>
-->