<div class="dr-container">

    <div class="dr-box-padding flexbox  sui-text-large" style="padding:20px; border: 0px;">
        <a class="sui-text-large flex" href="<?=R('book/detail/'. $book['book_id'])?>"><?=$book['book']?></a>
        <div>
            <?php if( !$bookJoin): ?>
                <a href="javascript:;" class="sui-btn btn-bordered  btn-primary addbook" data-bookid="<?=$book['book_id']?>">加入</a>
            <?php else: ?>
                <a href="javascript:;" class="sui-btn btn-bordered" data-bookid="<?=$book['book_id']?>">已加</a>
            <?php endif; ?>
            <i class="sui-icon icon-tb-friendadd"></i> <?=$book['user_cnt']?>
            <i class="sui-icon icon-tb-message"></i> <?=$book['discuss_cnt']?>
        </div>
        <div style="position: relative;width: 50px;" ><a class="dr-box-hover " href="<?=R('book/detail/'. $book['book_id'])?>"  style="width: 40px; height: 50px; position: absolute;top: -30px;right: -5px;"><img src="<?=H($book['book_img'])?>" ></a></div>
    </div>

    <div class="sp-v2">
        <div class="sp6">
            <div class="dr-box-padding"  >
                <div class="topic-header">
                    <h2 class="topic-head"><?=$topic['topic']?></h2>
                    <div class="flexbox">
                        <div class="flex">发表于 <?=date("Y-m-d H:i",$topic['ctime'])?> <?php if(isset($topic['attr'][31])): ?><span class="sui-label label-success">置顶</span> <?php endif; ?>

                            <?php if(isset($topic['attr'][32])): ?><span class="sui-label label-warning">精华</span> <?php endif; ?></div>
                        <div><?php if($topic['word_cnt']>0): ?>字: <?=$topic['word_cnt']?> | <?php endif; ?>查看: <?=$topic['view_cnt']?> | 回复: <?=$topic['comment_cnt']?></div>
                    </div>
                </div>
                <div class="dr-box-content sui-text-large">
                    <?php if($checkUser['bookAdmin']|| $checkUser['create'] || $checkUser['schoolAdmin']): ?>
                        <div class="sui-form sui-text-right" style="margin: 0" >打分：
                            <?php foreach ($topic_attr[41]['keys'] as $k5=>$v5  ) :?>
                            <label class="checkbox-pretty inline <?=($topic['attr'][41][$_cu['uid']][0]['attr']== $k5)?'checked':''?>">
                                <input  type="radio" <?=($topic['attr'][41][$_cu['uid']][0]['attr']== $k5 )?'checked="checked"':''?> name="r41" class=" ajax-url"  data-url="<?=R('book/attr/41/'.$topic['topic_id'].'/'.$k5 )?>"><span><?=$v5?></span>
                            </label>
                            <?php endforeach; ?>
                        </div>
                    <?php endif;?>

                    <?php
                    $is_show_fen  =  !($topic['tag_id']==3|| $topic['tag_id']==0 )   && !$topic['is_html'] ;//彭老师 要求先不打分
                    $is_xiangsi= $topic['sim']>4000;
                    if(   ( $_cu['uid']==$topic['user_id'] || $_is_teacher==3 ) &&  ($is_show_fen || $is_xiangsi ||  count( $topic['attr'][41])>0 )   ): ?>
                        <!-- 仅自己和老师可见  -->
                        <div class="sui-msg msg-info msg-block  ">
                            <div class="msg-con">
                                仅自己和老师可见
                                <ul>
                                    <?php if(  $is_show_fen ):?>
                                    <li>机分：<?php if( $topic['score']<0):?>正在打分请稍后，等不急可点<a href="javascript:;" class="ajax-url" style="color: #ff7300" data-url="<?=R('book/topicOther/dafen/'. $topic['topic_id'])?>" >这里更新</a>
                                        <?php else:?><?=Score( $topic['score'])?><?php endif;?>
                                    </li>
                                    <?php endif; ?>

                                    <?php $ik=0; foreach ( $topic['attr'][41] as $v ): foreach ($v as  $var) : $ik++; ?>
                                    <li><?=$user[$var['user_id']]['name']?> 于<?=date("Y-m-d H:i",$var['ctime'])?> 打分为 <?=$topic_attr[41]['keys'][$var['attr']]?></li>
                                    <?php endforeach; endforeach;?>
                                    <?php if($is_xiangsi):?>
                                        <li>
                                            <span class="sui-label label-warning dr-sim-bt dr-pointer" data-topic_id="<?=$topic['topic_id']?>" title="查看相似详情" >相似</span>
                                            <?php if( $_is_admin || $_is_school ):?><a href="javascript:;" class="ajax-url"  data-url="<?=R('book/topicOther/del_xs/'. $topic['topic_id'])?>" >擦除</a><?php endif;?>
                                        </li>
                                    <?php endif;?>
                                </ul>
                            </div>
                            <s class="msg-icon"></s>
                        </div>
                    <?php endif;?>

                    <?php if($topic['topic_info_yanwen'] ):?>
                        <div class="sui-msg msg-large msg-warning msg-block  ">
                            <div class="msg-con">
                                原文：
                                 <p><?=nl2br($topic['topic_info_yanwen'])?></p>
                            </div>
                            <s class="msg-icon"></s>
                        </div>
                    <?php endif;?>

                    <?php if( $topic['tag_id']==3):?>
                        <div class="flexbox">
                            <div class="head-div"><img src="<?= H($user[$topic['user_id']]['head'] )?>"></div>
                            <div class="flex">
                                <div class="pg-msg-content mp3play" data-file="<?=$topic['yin2']['file']?>" style="width: 30%;" ><i  class="sui-icon icon-tb-notification"></i> <span>试听</span></div>
                                <div style="clear: both;"></div>
                                <div style="margin: 10px 0 0 10px; "><?=nl2br($topic['yin']['topic_info'])?></div>
                            </div>
                        </div>
                    <?php else:?>

                    <div class="dr-topic-content"><?=$topic['is_html']?$topic['topic_info']:nl2br($topic['topic_info'])?></div>
                    <?php endif; ?>
                </div>
                <?php if( $_cu): ?>
                <div class="topic-href sui-text-right">
                    <span><a href="javascript:;" class="topic-bao" data-url="11/<?=$topic['topic_id']?>">举报</a>  |  </span>
                    <?php if( $topic['user_id']== $_cu['uid']): ?>
                        <span><a href="javascript:;"  class="ajax-url" data-url="<?=R('book/topicDel/'.$topic['topic_id'])?>">删除</a>  |  </span><?php  endif; ?>

                    <?php if( $topic['user_id']== $_cu['uid'] and $topic['is_html']  ): ?>
                        <span><a href="<?=R('book/topicForm/modify/'.$topic['topic_id'])?>" >编辑</a>  |  </span>
                    <?php elseif( $topic['user_id']== $_cu['uid'] ):?>
                        <span><a href="javascript:;" class="iframe-url" data-url="<?=R('book/topicForm/modify/'.$topic['topic_id'])?>">编辑</a>  |  </span>
                    <?php  endif; ?>

                    <?php if( $checkUser['bookAdmin']|| $checkUser['create'] || $checkUser['schoolAdmin']): ?>
                        <span><a href="javascript:;" class="ajax-url" data-url="<?=R('book/attr/31/'.$topic['topic_id'])?>">
                                <?php if(isset($topic['attr'][31])): ?>取消<?php else:?>设置<?php endif; ?>置顶</a>  |  </span> <?php endif;?>
                    <?php if($checkUser['bookAdmin']|| $checkUser['create'] || $checkUser['schoolAdmin']):?>
                        <span><a href="javascript:;" class="ajax-url" data-url="<?=R('book/attr/32/'.$topic['topic_id'])?>">
                            <?php if(isset($topic['attr'][32])): ?>取消<?php else:?>设置<?php endif; ?>精华</a>  |  </span><?php endif;?>
                    <span  class="topic-good dr-pointer" data-good="<?=$topic['good_cnt']?>" data-url="1/<?=$topic['topic_id']?>">赞(<?=$topic['good_cnt']?>) </span>
                </div>
                <?php endif; ?>
            </div>

            <?php if( $topic['comment_cnt']>0): ?>
            <div class="dr-box-padding"  >
                <div style="padding-top:10px ; ">
                <ul class="sui-nav nav-tabs nav-large nav-primary book-nav">

                    <li <?php if(!$_GET['order']): ?>class="active"<?php endif; ?> ><a href="<?=R('book/topic/'. $topic['topic_id'])?>">最新评论</a></li>
                    <li <?php if('1'==$_GET['order']): ?>class="active"<?php endif; ?> ><a href="<?=R('book/topic/'. $topic['topic_id'],['order'=>1])?>">正序查看</a></li>
                    <li <?php if('2'==$_GET['order']): ?>class="active"<?php endif; ?> ><a href="<?=R('book/topic/'. $topic['topic_id'],['order'=>2])?>">热门查看</a></li>
                </ul>
                </div>

                <div class="dr-box-content topic-comment-list">
                    <?php foreach ( $comments['list'] as $k=> $comment) : ?>
                    <div class="dr-list hover-show">
                        <div class="flexbox ">
                            <div class="head-small"><img src="<?=H($user[$comment['user_id']]['head'])?>"></div>
                            <div class="flex comment-w">
                                <a href="<?=R('book/user/'.$comment['user_id'] )?>"><?=$user[$comment['user_id']]['name']?></a>  <span class="des2">发表于 <?=date("Y-m-d H:i",$comment['ctime'])?> </span>

                                <div class="comment sui-text-large"> <?=nl2br($comment['comment'])?></div>
                            </div>
                            <div class="comment-num"><?php if($comment['word_cnt']>0): ?> <span class="des2"><?=$comment['word_cnt']?>字</span> <?php endif; ?><?=$k+1?>楼</div>
                        </div>
                        <?php if( $_cu): ?>
                        <div class="sui-text-right topic-href" data-topic_id="<?=$topic['topic_id']?>"   data-comment_id="<?=$comment['comment_id']?>"  data-book_id="<?=$book['book_id']?>">
                            <span class="hover-show-hide"><a href="javascript:;" class="topic-bao" data-url="21/<?=$comment['comment_id']?>">举报</a>  |  </span>
                           <span>  <a href="javascript:;" class="topic-reply" data-op="none">回复</a>  |  </span>
                            <?php if( $_cu['uid']==$comment['user_id']): ?> <span><a href="javascript:;" class="topic-del">删除</a>  |  </span><?php endif; ?>
                            <span  class="topic-good dr-pointer" data-good="<?=$comment['good_cnt']?>" data-url="2/<?=$comment['comment_id']?>">赞(<?=$comment['good_cnt']?>)</span>
                        </div>
                        <?php endif; ?>

                    </div>
                    <?php endforeach; ?>
                    <?php if($comments['page']):?>
                    <div class="dr-page"><?=$comments['page']?></div>
                    <?php endif;?>

                </div>
            </div>
            <?php endif;?>
            <?php if(!$_cu): ?>
                <div class="dr-box-padding comment-form">
                    <div class="dr-box-content">
                        <div class="dr-no-content">登录后可回复！<a href="<?=R('login')?>" class="sui-btn btn-bordered btn-primary">登录</a></div>
                    </div>
                </div>

            <?php
            elseif( ! (isset( $topic['attr'][33])  )):
            ?>
            <div class="dr-box-padding comment-form">
                <div class="dr-box-content flexbox ">
                    <div class="head"><img src="<?=H($_cu['head'])?>"></div>
                    <form class="flex"  action="<?=R('book/commentAdd/'.$topic['book_id'].'/'.$topic['topic_id'])?>" id="commentAdd">
                        <div class="dr-from-group"><textarea name="comment" class="comment input-100 sui-text-large" id="comment"></textarea></div>
                        <div class="flexbox">
                            <div class="flex"><button class="sui-btn  btn-primary btn-xlarge commentAdd">提交</button> </div>
                            <div class="des2"><?php if($book['word_comment']>0 ):?>要求不少于<b><?=$book['word_comment']?></b>字<?php endif;?> 已经输入<span class="word_count">0</span>字</div>
                        </div>
                        <input type="hidden" value="0" name="word_cnt" id="word_cnt"  />
                    </form>
                </div>
            </div>
            <?php endif; ?>


        </div>

        <div class="sp3">
            <div class="dr-box-padding sui-text-center sui-text-large"  >
                <div class="dr-box-content" style="padding: 20px ; ">
                    <div class="head-large"><img src="<?=H($user[$topic['user_id']]['head'])?>"></div>
                    <h3><a href="<?=R('book/user/'.$topic['user_id'])?>"><?=$user[$topic['user_id']]['name']?></a></h3>
                    <div><?=$user[$topic['user_id']]['school']?></div>
                    <?php if($topic['is_teacher']==3):?> <div class="sui-text-warning" title="通过人工认证实为真实教师" ><i class="sui-icon icon-tb-vip"></i>认证教师</div> <?php endif;?>
                    <!-- <div class="des2">物理0212</div> -->
                </div>
            </div>

            <?php include  tplFile("book/i_add.phtml"); ?>
        </div>
    </div>
</div>

<div id="f-hide" style="display: none">
    <div class="comment-replay-from flexbox">
        <div class="head-small"><img src="<?=H($_cu['head'])?>"></div>
        <div class="sui-text-right flex">
            <div class="dr-from-group"><input name="comment" class="input-100 comment" placeholder="回复@:"  /></div>
            <div><button class="sui-btn  btn-primary">回复</button></div>
            <input type="hidden" value="0" name="word_cnt" class="word_cnt"  />
        </div>
    </div>
</div>

<?php include "op_select_class.phtml" ;?>

<?php  if($topic['sim']>3000)  include tplFile( "op_sim.phtml" ); ?>
<?php if($topic['tag_id']==3):?>
    <div id="jquery_jplayer"></div>
    <script src="<?=$_cdn?><?=$WWW_RES?>/js/plupload/plupload.full.min.js"></script>
    <script src="<?=$_cdn?><?=$WWW_RES?>/js/jplayer/jquery.jplayer.min.js"></script>
<?php endif; ?>
<script>
    $(function () {
        $('.commentAdd').click( function () {
            var str = $('#comment').val();
            $('#word_cnt').val( DR.wordCount(str));
            DR.ajaxForm( 'commentAdd' );
            return false ;
        });
        $('.addbook').click( BOOK.addBook );

        $('.topic-reply').click( BOOK.reply  );
        $('.topic-good').click( BOOK.good   );
        $('.topic-bao').click( BOOK.juBao   );
        $('.ajax-url').click( BOOK.ajaxUrl    );
        $('.iframe-url').click( BOOK.iframe );
        $('.topic-del').click( function () {
            var that = $(this);
            var ui={
                p1:that.parents( '.topic-href'),
                p2:that.parents( '.dr-list')
            }

            DR.ajax( DR.R('book/commentDel/'+ ui.p1.data('comment_id') ),{},{'success':function () {
                ui.p2.hide();
                DR.tip("删除成功",{'style':'success'} );
            }} )
        }  );
        var ui2={  word_count:$('.word_count') }
        $('#comment').keyup(function () {
            var str= this.value;
            ui2.word_count.html( DR.wordCount(str) );
        });
        <?php if($topic['tag_id']==3):?>
        DR.play( $("#jquery_jplayer"),'.mp3play' );
        <?php endif; ?>
        <?php  if($topic['sim']>3000) : ?>
        var cl_sim= new haoceSim();
        $('.dr-sim-bt').click( function () {
            var topic_id = $(this).data('topic_id');
            DR.log('topic_ID ',topic_id );
            cl_sim.simByTopicID( topic_id );
        });
        <?php endif; ?>
    });
</script>