<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title><?=($site_title?$site_title.'-':'')?>好策</title>
   <!--
    <link href="<?=$WWW_RES?>/sui/css/sui.min.css" rel="stylesheet">
    <link href="<?=$WWW_RES?>/js/art/dialog.css" rel="stylesheet">
    -->
    <link href="<?=$WWW_RES?>/css/dr.css" rel="stylesheet">
    <script type="text/javascript" src="//g.alicdn.com/sj/lib/jquery/dist/jquery.min.js"></script>
    <!--
    <script type="text/javascript" src="<?=$WWW_RES?>/sui/js/sui.min.js"></script>
    <script type="text/javascript" src="<?=$WWW_RES?>/js/dr.js"></script>
    <script type="text/javascript" src="<?=$WWW_RES?>/js/art/dialog.js"></script>
    -->
    <script type="text/javascript" src="<?=$_cdn?><?=$WWW_RES?>/hcapp/js/vue.min.js"></script>

    <style>
        body{margin: 0 auto;padding: 0; }
        .dr-box-padding{border: 0px; }
        .ad-head2{height:60px; background-color: #fff;  position: relative; margin: 0 auto; color: #666}
        .ad-head-link{ margin : 15px 15px 0 0;}
        .ad-head-link i{   display: inline-block;  width: 20px;  text-align: center; font-size: 12px;  color: #ccc;     font-family: \5b8b\4f53;font-style: normal; }
        .ad-head-link a{ display: inline-block; color: #666; text-decoration:none; font-size: 14px;}
        .ad-head-link a:hover{ text-decoration:underline; }
        .ad-head-menu{ position: absolute; width: 190px; top:61px; bottom: 50px; background-color: #f6f7fb;   list-style: none; padding: 0;  }
        .ad-head-iframe{ position: absolute; top:61px; left: 191px;right: 0; bottom: 50px; background-color: #fff; z-index: 10 }
        .ad-head-top{ position: absolute; top:65px; left: 200px; font-size: 14px;display: none; }


        .ad-head-menu a{display: block; padding: 8px; text-decoration:none;  color:#333;font-size: 14px;   }
        .ad-head-menu a:hover, .ad-head-menu .select{background-color: #00a0e9; text-decoration:none; color:#fff }
        ul,li{ margin: 0; padding: 0px; display: block;  }
        .leafmenu{ display: none    }
        .leafmenu li a{   padding-left: 22px; position: relative;  }
        .leafmenu li a:before{content: " ";background-color: #666; position: absolute; top:16px; left:12px; width: 6px;height:6px;overflow: hidden;border-radius: 2px;}
        .leafmenu li a:hover:before, .ad-head-menu .select:before{ background-color: #fff; }
        .logo-txt{padding-top: 20px; padding-left: 15px; display: block; text-decoration:none;}
        .ad-head-open{ background-color: #fff; }

        .menu-one{  position: relative;  }
        .menu-one:before{ content: " "; background-color: #666; position: absolute;   top:16px; right:12px; width: 12px;height:6px;overflow: hidden; background: url("/res/img/arrow.png") no-repeat;  }
        .ad-head-open .menu-one:before{ background: url("/res/img/arrow.png") no-repeat  right 0; }
        .ad-head-open  .leafmenu{ display: block    }
    </style>
</head>
<body style="background-color: #e8ecf0">
<div class="ad-head2">
    <div class="flexbox">
        <div class="flex"><a class="logo-txt" href="<?=R('school')?>" ><?=$site_title?> </a></div>
        <div class="ad-head-link">
            <a  >欢迎<?=$_cu['name']?>回来</a><i>|</i>
            <a href="/">返回好策</a><i>|</i>
            <a href="<?=R('logout')?>">登出</a>
        </div>
    </div>
</div>

<ul class="ad-head-menu">

    <li> <a  href="javascript:;" data-url="<?=R('school/userList')?>"  >成员管理</a></li>
    <!--

    -->
    <li> <a  href="javascript:;" data-url="<?=R('school/bookList')?>">读书管理</a></li>
    <?php if( $block  ):?>
        <li> <a  href="javascript:;" data-url="<?=R('school/classList' )?>">班级管理</a></li>
        <?php foreach( $block as $v):?>
            <li>
                <a class="menu-one" href="javascript:;"><?=$v['block']?></a>
                <ul class="leafmenu">
                    <li> <a  href="javascript:;" data-url="<?=R('school/block/list/'.$v['block_id'] )?>">书单&设置</a></li>
                    <li> <a  href="javascript:;" data-url="<?=R('school/novelView?tb=list&block_id='.$v['block_id'] )?>" >选书用户</a>  </li>
                    <li> <a  href="javascript:;" data-url="<?=R('school/novelView?tb=list&show=bar&block_id='.$v['block_id'] )?>" >进度可视化</a>  </li>
                    <li> <a  href="javascript:;" data-url="<?=R('school/novelViewTj?block_id='.$v['block_id'] )?>" >每日趋势</a>  </li>
                    <li> <a  href="javascript:;" data-url="<?=R('school/classList/block?block_id='.$v['block_id'] )?>">班级管理</a></li>
                    <li> <a  href="javascript:;" data-url="<?=R('school/schoolUser1001?block_id='.$v['block_id'] )?>">白名单</a></li>
                </ul>
            </li>
         <?php endforeach; ?>
    <?php else: ?>
        <li> <a  href="javascript:;" data-url="<?=R('school/classList/school/'.$term_conf['term_key'])?>">班级管理</a></li>
    <?php endif; ?>

    <li >
        <a class="menu-one" href="javascript:;">学期</a>
        <ul class="leafmenu">
            <li> <a  href="javascript:;" data-url="<?=R('school/userTermList')?>">学期统计</a></li>
            <li> <a  href="javascript:;" data-url="<?=R('school/termList')?>">学期管理</a></li>
            <?php if($term_conf['is_school_user']):?>  <li> <a  href="javascript:;" data-url="<?=R('school/schoolUserList')?>">白名单</a></li><?php endif; ?>
        </ul>
    </li>

    <li >
        <a class="menu-one" href="javascript:;">阅读可视化</a>
        <ul class="leafmenu">
            <li> <a  href="javascript:;" data-url="<?=R('school/novelViewTj')?>">每日趋势</a></li>
            <li> <a  href="javascript:;" data-url="<?=R('school/novelView?tb=list&show=bar')?>">阅读进度可视化</a></li>
            <!--
            <li> <a  href="javascript:;" data-url="<?=R('school/novelViewTj/rank')?>">阅读榜单</a></li>
            -->
            <li> <a  href="javascript:;" data-url="<?=R('school/novelView?tb=list')?>">阅读进度记录</a></li>
            <li> <a  href="javascript:;" data-url="<?=R('school/novelView?tb=dict')?>">查词记录</a></li>
            <li> <a  href="javascript:;" data-url="<?=R('school/novelView?tb=comment')?>">读书笔记</a></li>
        </ul>
    </li>

    <li> <a  href="javascript:;" data-url="<?=R('school/rank')?>"  >榜单</a></li>
    <!--
    <li >
        <a class="menu-one" href="javascript:;">设置</a>
        <ul class="leafmenu">
            <li> <a  href="javascript:;" data-url="<?=R('school/setting/index')?>">首页区块</a></li>
        </ul>
    </li>
    -->


</ul>
<div class="ad-head-top">
  <span>菜单名称</span>
</div>
<div class="ad-head-iframe" style="overflow: hidden">
    <iframe src="<?=R('school/main')?>" style="width: 100%; height: 100%;border: 0px; overflow:auto " id="ad-iframe"></iframe>
</div>

<?php
include "footer.phtml";
?>

</body>

<script>
    $(function () {
        var ui={
            iframe:$('#ad-iframe')
            ,a: $('.ad-head-menu a')
            ,menu: $('.menu-one')
        };
        ui.a.click(function () {
            var that = $(this);
            var url = that.data('url');
            if( 'undefined'== typeof  url ) return false ;
            ui.iframe.attr('src', url );
            ui.a.removeClass('select' );
            that.addClass('select');
            return false ;
            //alert( url );
        });
        ui.menu.click(function () {
            var that = $(this);
            var pli = that.parents( 'li');
            var clname = pli.attr('class');

            if('undefined' != typeof  clname && clname.indexOf( 'ad-head-open')>=0) pli.removeClass( 'ad-head-open');
            else pli.addClass( 'ad-head-open');
        });
    });
</script>

</html>



