<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>功能控制台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <style>
        body{ margin: 0 auto; background-color: #f7f7f7}
        .dui-content{ max-width: 600px; margin: 0 auto; }

        .pay-btn{ background-color:#4cb9fc ; border: 1px solid #33affc; color: #fff;text-decoration:none;
            display: inline-block; padding: 5px 14px;box-sizing: border-box; margin-bottom: 0;    font-size: 14px;            line-height: 18px;
            text-align: center;    vertical-align: middle;    cursor: pointer;  border-radius: 2px;
            user-select: none;width: 160px;
        }
        .pay-btn-back{ padding-top: 2px;  padding-bottom: 2px; font-size: 12px; width: 100px;     background-color: transparent;
            border: 1px solid #33affc;          color: #33affc;   }
    </style>
</head>
<body>
<div class="dui-content" id="dui-qr-pay">
    <div style=" padding-top: 20px;">控制台</div>
    <ul>
        <li><a href="https://c1.crosscase.cn/console" target="c1">控制台1-五星</a> </li>
        <li><a href="https://c2.crosscase.cn/console" target="c2">控制台2-优优</a> </li>
        <li><a href="https://c3.crosscase.cn/console" target="c3">控制台3-九九</a> </li>
        <li><a href="https://c4.crosscase.cn/console" target="c4">控制台4-淘金</a> </li>
        <li><a href="https://c5.crosscase.cn/console" target="c5">控制台5-开心</a> </li>
        <li><a href="https://c6.crosscase.cn/console" target="c6">控制台6-星河</a> </li>
        <li><a href="https://c7.crosscase.cn/console" target="c7">控制台7-凤凰</a> </li>
    </ul>
    <div style=" padding-top: 20px;">其他</div>
    <ul>
        <li><a href="https://cw.crosscase.cn/finance" target="cw">财务</a> </li>
        <li><a href="/look" target="look">大看盘</a> </li>
    </ul>
    <!--
    <div style="text-align: center;padding-top: 20px;"><button class="pay-btn" onclick="pay()">重新支付</button></div>
    <div style="padding-top: 30px;text-align: center;color: #999;font-size: 12px;">请确保手机有安装支付宝！</div>
    <div style="text-align: center;padding-top: 20px;"><button class="pay-btn pay-btn-back" onclick="back()">返回商城</button></div>
    -->
</div>
</body>
<script>

</script>
</html>

