
<link href="<?=$_cdn?><?=$WWW_RES?>/sui/css/sui.min.css" rel="stylesheet">
<script type="text/javascript" src="<?=$_cdn?><?=$WWW_RES?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?=$_cdn?><?=$WWW_RES?>/sui/js/sui.min.js"></script>


<link href="<?=$_cdn?><?=$WWW_RES?>/js/art/dialog.css" rel="stylesheet">
<link href="<?=$_cdn?><?=$WWW_RES?>/css/dr.css?d=20180928" rel="stylesheet">
<link href="<?=$_cdn?><?=$WWW_RES?>/css/iconfont/iconfont.css" rel="stylesheet">
<!--  -->
<script type="text/javascript" src="<?=$_cdn?><?=$WWW_RES?>js/dr.js?d=2005"></script>
<script type="text/javascript" src="<?=$_cdn?><?=$WWW_RES?>/js/art/dialog.js"></script>

