<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title><?=($site_title?$site_title.'-':'')?>好策</title>
    <?php
    include "header.phtml";
    ?>
<style>
    .dr-box-padding{border: 0px; }
</style>
</head>
<body style="background-color: #fff">

<?php
include $tpl_file;
?>


</body>

</html>



