<?php
use model\drFun;
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title><?=($site_title?$site_title.'-':'')?> HI PAY</title>
    <?php
    include "header.phtml";
    ?>

</head>
<body>
<!--
<div class="sui-navbar  navbar-fixed-top">
    <div class="navbar-inner">
        <div class="dr-container">
            <a href="<?=WWW_ROOT?>" class="sui-brand">群富</a>
            <ul class="sui-nav">
                <li ><a href="<?=WWW_ROOT?>">首页</a></li>
            </ul>
        </div>
    </div>

</div>
<div style="height: 60px">  </div>

-->
<?php
include $tpl_file;
?>
</body>
<?php
include "drtip.phtml";
?>


</html>



