
<div class="dr-sim" style="display: none;">
    <div class="dr-sim-close"><i class="icon-tb-close sui-icon"></i></div>
    <div class="dr-sim-m">
        <div class="dr-sim-head">
            <div class="dr-sim-radius"><b>80</b><span>.5%</span></div>
        </div>

        <div class="dr-sim-left ">
            <div class="dr-sim-item">
                <h4>梯田</h4>
                <div class="dr-sim-content">

                </div>
            </div>
        </div>
        <div class="dr-sim-right">
            <div class="dr-sim-item">
                <h4>梯田2</h4>
                <div class="dr-sim-content">

                </div>
            </div>
        </div>
        <div style="clear: none;"></div>
    </div>
</div>
<script type="text/javascript" src="<?=$_cdn?><?=$WWW_RES?>/js/haoce.sim.js?d=20180106"></script>