
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>获得支付宝红包</title>
</head>
<body>
<style type="text/css">
    *{margin:0; padding:0;}
    img{max-width: 100%; height: auto;}
    .test{height: 600px;  font-size: 40px;}
</style>
<div class="test">
    <?php if( $client==6):?>
    <p style="padding: 50px 10px 10px 10px;">恭喜获得你支付宝现金红包，请使用浏览器打开领取<?=$client?></p>
    <?php else:?>
        <p style="padding: 30px 10px 10px 10px;text-align: center">请使用支付宝扫一扫领取</p>
    <div style="text-align: center"><img src="/res/weixinTip/2.jpg"></div>
    <?php endif; ?>
</div>
<script type="text/javascript">
    function is_weixin() {
        var ua = navigator.userAgent.toLowerCase();
        if (ua.match(/MicroMessenger/i) == "micromessenger") {
            return true;
        } else {
            return false;
        }
    }
    var isWeixin = is_weixin();
    var winHeight = typeof window.innerHeight != 'undefined' ? window.innerHeight : document.documentElement.clientHeight;
    function loadHtml(){
        var div = document.createElement('div');
        div.id = 'weixin-tip';
        div.innerHTML = '<p><img src="/res/weixinTip/live_weixin.png" alt="微信打开"/></p>';
        document.body.appendChild(div);
    }

    function loadStyleText(cssText) {
        var style = document.createElement('style');
        style.rel = 'stylesheet';
        style.type = 'text/css';
        try {
            style.appendChild(document.createTextNode(cssText));
        } catch (e) {
            style.styleSheet.cssText = cssText; //ie9以下
        }
        var head=document.getElementsByTagName("head")[0]; //head标签之间加上style样式
        head.appendChild(style);
    }
    var cssText = "#weixin-tip{position: fixed; left:0; top:0; background: rgba(0,0,0,0.8); filter:alpha(opacity=80); width: 100%; height:100%; z-index: 100;} #weixin-tip p{text-align: center; margin-top: 10%; padding:0 5%;}";
    if(isWeixin){
        loadHtml();
        loadStyleText(cssText);
    }
</script>
</body>
</html>